### ISSUE TITLE
Suppress ImageJ GUI?

### ISSUE THREAD

**Issue by ma-sadeghi** [imagej/pyimagej#102]
Is there a way to force `pyimagej` not to show the GUI while processing?

**Comment by imagejan** [comment]
By default, it should initialize without a GUI, unless you specify `headless=False`, see [Initialization.md](https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md#ways-to-initialize).

How are you running `pyimagej` when you see the GUI being shown? What operating system? Which version?

**Comment by ma-sadeghi** [comment]
@imagejan Thanks. I'm using it on Windows (v1.0.0). Let me back up, I'm interested to run plugins headless, for instance the following code snippet (take from your docs):
```python
import imagej
ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
ij.py.run_macro("""run("Blobs (25K)");""")
blobs = ij.py.active_image_plus()
ij.py.show(blobs)

plugin = 'Mean'
args = {
    'block_radius_x': 10,
    'block_radius_y': 10            
}
ij.py.run_plugin(plugin, args)
imp = ij.py.active_image_plus()
ij.py.show(imp)
```

**Comment by ctrueden** [comment]
@ma-sadeghi The code snippet you posted works for me, after changing `2.0.0-pre-10` to `2.1.1` (the latest release of Fiji). Is it working on your system?

**Comment by ma-sadeghi** [comment]
@ctrueden Yep, it does work, but I want it to run in headless mode. Sorry if my question seems very basic. I was just introduced to `pyimagej`.

**Comment by ma-sadeghi** [comment]
@ctrueden Btw, I get these warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.imagej.patcher.LegacyInjector (file:/C:/Users/Amin/.jgo/net.imglib2/imglib2-imglyb/1.0.0+net.imagej-imagej-legacy-RELEASE+sc.fiji-fiji-2.1.1/ij1-patcher-1.1.0.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of net.imagej.patcher.LegacyInjector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by ma-sadeghi** [comment]
@ctrueden One more thing, I don't exactly know how to reproduce this behaviour, but sometimes when I run the same script (I use IPython console inside Spyder IDE), I get the following error:
```bash

  File "c:\users\amin\code\porespy\porespy\imagej\__funcs__.py", line 38, in imagej_wrapper
    ij = imagej.init(path, headless=False)

  File "C:\Users\Amin\anaconda3\envs\sci\lib\site-packages\imagej\__init__.py", line 214, in init
    WindowManager = JObject(_WindowManager)

  File "C:\Users\Amin\anaconda3\envs\sci\lib\site-packages\jpype\_jobject.py", line 59, in __new__
    return _JObjectFactory(*args, **kwargs)

  File "C:\Users\Amin\anaconda3\envs\sci\lib\site-packages\jpype\_jobject.py", line 111, in _JObjectFactory
    return tp._cast(v)

TypeError: Unable to cast 'type' to java type 'java.lang.Class'
```
