### ISSUE TITLE
'net.imagej.ImageJ' object has no attribute 'legacy_enabled'

### ISSUE THREAD

**Issue by xianghuix** [imagej/pyimagej#105]
when getting the ImageJ1 ij.WindowManager using the ij.py.window_manager() function, an AttributeError is popped up
AttributeError: 'net.imagej.ImageJ' object has no attribute 'legacy_enabled'

The problem seems being fixed by changing line 685 in imagej.init from
"if not ij.legacy_enabled:"
to
"if not ij.legacy.isLegacyMode():"

**Comment by elevans** [comment]
Hi @xianghuix,

You are correct, thanks for spotting this! I've submitted a PR to fix this bug.
