### ISSUE TITLE
Unable to initialize imagej with `sc.fiji:fiji` endpoint

### ISSUE THREAD

**Issue by elevans** [imagej/pyimagej#108]
The latest build of fiji breaks pyimagej initialization when using the `sc.fiji:fiji` endpoint:

```python
>>> import imagej
>>> ij = imagej.init('sc.fiji:fiji')
...
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/Documents/software/anaconda/envs/pyij/lib/python3.8/site-packages/imagej/__init__.py", line 168, in init
    ij = ImageJ()
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService
```

As a workaround, specifying a different version of fiji works:

```python
>>> import imagej
>>> ij = imagej.init('sc.fiji:fiji:2.1.1')
>>> ij.getVersion()
'2.1.0/1.53c'
```
This is due to (from what I understand) the unintended inclusion of `FilamentDetector` in the core fiji package and it's dependence on JavaFX, which is not shipped with the conda flavors of `openjdk`.

**Comment by ctrueden** [comment]
The inclusion of `FilamentDetector` into Fiji core was intended. The fact that it crashes the SciJava context upon initialization of its `GUIStatusService` is a bug.

**Comment by hinerm** [comment]
@ctrueden filament detector is built on JavaFX and so IMO shouldn't be a part of the core Fiji update sites until the time that Fiji ships JavaFX or provides a mechanism for its acquisition.

**Comment by ctrueden** [comment]
We need to start shipping JavaFX with Fiji. `FilamentDetector` is not the only component requiring it. There is also `OMEVisual`. And some update sites ship components that use it, too. The intent has always been that JavaFX be available with Fiji. I would be against removing `FilamentDetector` from the Fiji distribution just because we haven't solved JavaFX deployment.

**Comment by hinerm** [comment]
Works as of #140 being fixed.
