### ISSUE TITLE
How to add ImageJ 1.x support for a local installation?

### ISSUE THREAD

**Issue by lollows** [imagej/pyimagej#111]
Q: I want to use the ImageJ1-based plugins from a local installation. According to the [Initialization.md](https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md#including-imagej-1x-support), I try to use `ij = imagej.init([r'D:\packages\ImageJ_fiji', 'net.imagej:imagej-legacy'], headless=False)`. However, it gives an error as follows.
```bash
 `C:\Users\Administrator\anaconda3\envs\pyij\Library\bin\mvn.CMD -B -f C:\Users\Administrator\.jgo\net.imglib2\imglib2-imglyb\1.0.0+D-\packages\ImageJ_fiji-RELEASE+net.imagej-imagej-legacy-RELEASE\pom.xml dependency:resolve': 1
```
The ImageJ2 installation `ij = imagej.init(r'D:\packages\ImageJ_fiji', headless=False)` works fine. Please let me know if I missed something. Thank you.

**Comment by lollows** [comment]
Sorry to submit duplicate issues,. As the github has just gone crazy, I can't see the previous commits.

**Comment by imagejan** [comment]
For the record: duplicate of #112.
