### ISSUE TITLE
set JAVA_HOME for jpype

### ISSUE THREAD

**Issue by oeway** [imagej/pyimagej#116]
Hi 

I am wondering if pyimagej can set JAVA_HOME automatically for jpype, because currently it cannot find it and complains the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/imagej/__init__.py", line 162, in init
    sj.start_jvm()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/scyjava/__init__.py", line 56, in start_jvm
    jpype.startJVM(*options)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jpype/_core.py", line 187, in startJVM
    jvmpath = getDefaultJVMPath()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jpype/_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jpype/_jvmfinder.py", line 215, in get_jvm_path
    .format(self._libfile))
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try settingup the JAVA_HOME environment variable properly.
```

**Comment by oeway** [comment]
If we install jdk from conda, then we can use the path to the conda environment.

On binder for example, this works: `export JAVA_HOME=/srv/conda/envs/notebook`.

Therefore maybe we can using something like the following to set JAVA_HOME in pyimagej:
```
import sys
import os

# if JAVA_HOME is not set and we are in a conda environment
if not os.environ.get('JAVA_HOME') and not os.environ.get('CONDA_DEFAULT_ENV'):
    # infer the conda environment via sys.executable path
    os.environ['JAVA_HOME'] = os.sep.join(sys.executable.split(os.sep)[:-2])
```

**Comment by ctrueden** [comment]
@oeway We used to do that, when we were using pyjnius. But with the switch to jpype, we removed it:

scijava/scyjava@c31d63373389d498b17550d6fb55b98a02a03e86

Adding back some subset of this logic would be fine, if you have time. Or else @elevans, do you have time to do it?

**Comment by elevans** [comment]
TODO:
- [ ] Test pyimagej environment install on binder:
```python
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge pyimagej openjdk=8
```

**Comment by hinerm** [comment]
> Test pyimagej environment install on binder (a binder without openjdk):

I can confirm that this does not work, e.g. in an [ITK binder](https://hub-binder.mybinder.ovh/user/insightsoftware-tium-itkwidgets-400vr58f/lab/tree/examples/Mesh.ipynb)

**Comment by hinerm** [comment]
@oeway what environment were you running `pyimagej` in your original post?

From what I can tell, if we install using conda in a normal user workflow `JAVA_HOME` is set by conda when we activate our `pyimagej` environment.

It's also set in a Jupyter notebook that is initialized with `openjdk`.

It seems like it's only a problem with dynamic Jupyter initialization, in which case we're kind of bypassing the mechanisms built to solve this issue.. so my first thought is just to add `os.environ['JAVA_HOME'] = os.sep.join(sys.executable.split(os.sep)[:-2] + ['jre'])
` to the dynamic initialization script instead of managing the environment variables inside of pyimagej itself.

But am I missing a use case?

**Comment by oeway** [comment]
> @oeway what environment were you running `pyimagej` in your original post?
> 
> From what I can tell, if we install using conda in a normal user workflow `JAVA_HOME` is set by conda when we activate our `pyimagej` environment.
> 
> It's also set in a Jupyter notebook that is initialized with `openjdk`.
> 
> It seems like it's only a problem with dynamic Jupyter initialization, in which case we're kind of bypassing the mechanisms built to solve this issue.. so my first thought is just to add `os.environ['JAVA_HOME'] = os.sep.join(sys.executable.split(os.sep)[:-2] + ['jre']) ` to the dynamic initialization script instead of managing the environment variables inside of pyimagej itself.
> 
> But am I missing a use case?

Hi @hinerm Thanks for looking into this, I was testing it on Binder. If I remember correct, this was the repo: https://github.com/oeway/pyimagej-binder-image

You proposal for adding it to the dynamic intitialization script sounds good to me.

**Comment by hinerm** [comment]
Resolved in https://github.com/imagej/pyimagej/commit/c02c39ef825dadb5affaed6604ebe0383e857976
