### ISSUE TITLE
How to get headless=False work with Xvfb

### ISSUE THREAD

**Issue by oeway** [imagej/pyimagej#117]
Hi I am having trouble with starting pyimagej with headless=False. See below
Setup a virtual display
```bash
# set environment variables
export DISPLAY=:1

# execute run commands
Xvfb $DISPLAY -screen 0 1024x768x16 &
```

Then I start imagej with headless=False:
```python
import imagej
import os
ij = imagej.init(os.path.expanduser("~") + '/Fiji.app',headless=False)
ij.getVersion()
```

And here is the error:

```bash
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in org.scijava.AbstractGateway.getVersion()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in net.imagej.app.ToplevelImageJApp.getVersion()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in net.imagej.app.ToplevelImageJApp.getLegacyVersion()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in net.imagej.legacy.LegacyService.getVersion()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in net.imagej.legacy.IJ1Helper.getVersion()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in java.lang.reflect.Field.get()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in java.lang.reflect.Field.getFieldAccessor()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in java.lang.reflect.Field.acquireFieldAccessor()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in sun.reflect.ReflectionFactory.newFieldAccessor()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor()

/srv/conda/envs/notebook/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in sun.misc.Unsafe.ensureClassInitialized()

Exception: Java Exception

The above exception was the direct cause of the following exception:

java.lang.NoClassDefFoundError            Traceback (most recent call last)
<ipython-input-1-cd11d8009031> in <module>
      2 import os
      3 ij = imagej.init(os.path.expanduser("~") + '/Fiji.app',headless=False)
----> 4 ij.getVersion()

java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: Could not initialize class ij.ImageJ
```

Here is a binder image which you can test:

https://mybinder.org/v2/gh/oeway/pyimagej-binder-image/master?filepath=deepimagej-test-notebook-v0.1.2.ipynb

Note that I have already started the Xvfb in the binder instance: https://github.com/oeway/pyimagej-binder-image/blob/master/start

**Comment by hinerm** [comment]
@oeway I wasn't able to get the archived `Fiji.app` you're using to work headlessly. After updating it (`!/home/jovyan/Fiji.app/ImageJ-linux64 --update update`) or initializing with a remote endpoint (`imagej.init(headless=False)`) I had more success.

I had to use a [slightly different environment setup](https://github.com/hinerm/binder_pyimagej_test/tree/main/binder) for Xvfb. But this did allow [`imagej.init(headless=False)`](https://github.com/hinerm/binder_pyimagej_test/blob/main/headless_pyimagej.ipynb) to work. I found it helpful to confirm with `ij.legacy.isLegacyMode()`, which should return `True` if it thinks it has a UI.

Does that help at all?

**Comment by ctrueden** [comment]
@oeway Is this still an issue for you? Do you need additional help?

**Comment by oeway** [comment]
This works now!

However, we still observe different output for deepimagej, I.e. works in a desktop Fiji but failed in binder+xvbf+nonheadless. See here: https://forum.image.sc/t/error-when-calling-deepimagej-from-pyimagej/54199/3

**Comment by ctrueden** [comment]
I'd like to have an Xvfb example for the paper. We should use https://pypi.org/project/xvfbwrapper/ if possible because it's nice.

**Comment by ctrueden** [comment]
@hinerm As I said above, it would be nice to have an Xvfb example with xvfbwrapper for the paper. Is that being remembered anywhere, now that this issue is closed? Or did you and @elevans decide to overrule me on it?

**Comment by hinerm** [comment]
@ctrueden it's noted in our paper document.

**Comment by elevans** [comment]
@ctrueden Not overruled :). I'm working on an example now with the `RoiManager`.
