### ISSUE TITLE
Error in ij = imagej.init

### ISSUE THREAD

**Issue by rmd13** [imagej/pyimagej#122]
Hi, I am using pip to install pyimagej:
  # install pyimagej:
      # 1. install python3-spyder3
      # 2. instalL OpenJDK8  https://cdn.azul.com/zulu/bin/zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64.zip
          # unzip to D:\GreenSoft\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64
      # 3. install maven https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.zip
          # unzip to D:\GreenSoft\apache-maven-3.8.1\bin
          # test by running <mvn -v>. Note JAVA_HOME is required
          # then add D:\GreenSoft\apache-maven-3.8.1\bin to Path 
      # 4. pip install pyimagej
      # then running spyder3 that embedded in python3

Below is the error:(I tried all the demos of  imagej.init(*) but all produce the same kind of error

```
import imagej # runs ok
ij = imagej.init("D:\\GreenSoft\\Fiji.app") # error:
Traceback (most recent call last):

  File "<ipython-input-21-684fc5a6eed2>", line 1, in <module>
    ij = imagej.init("D:\\GreenSoft\\Fiji.app")

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\site-packages\imagej\__init__.py", line 162, in init
    sj.start_jvm()

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\site-packages\scyjava\__init__.py", line 51, in start_jvm
    verbose=scyjava.config.get_verbose()

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\site-packages\jgo\jgo.py", line 428, in resolve_dependencies
    os.makedirs(workspace, exist_ok=True)

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\rmd\\.jgo\\net.imglib2\\imglib2-imglyb\\1.0.0+net.imagej-imagej-RELEASE+net.imagej-imagej-RELEASE+net.imagej-imagej-RELEASE+net.imagej-imagej-RELEASE+net.imagej-imagej-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-legacy-RELEASE+net.imagej-imagej-2.1.0+sc.fiji-fiji-RELEASE'
```

**Comment by rmd13** [comment]
After I restart computer and re-run, the error now became:

```
ij = imagej.init("D:\GreenSoft\Fiji.app")
Traceback (most recent call last):

  File "<ipython-input-5-402eedeea987>", line 1, in <module>
    ij = imagej.init("D:\GreenSoft\Fiji.app")

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\site-packages\imagej\__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')

org.scijava.NoSuchServiceException: org.scijava.NoSuchServiceException: Service net.imagej.legacy.LegacyService not found.




ij = imagej.init()
Traceback (most recent call last):

  File "<ipython-input-6-a1762181331d>", line 1, in <module>
    ij = imagej.init()

  File "c:\users\rmd\appdata\local\programs\python\python36\lib\site-packages\imagej\__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')

org.scijava.NoSuchServiceException: org.scijava.NoSuchServiceException: Service net.imagej.legacy.LegacyService not found.
```

**Comment by rmd13** [comment]
After I restart computer, it is ok now.

**Comment by ctrueden** [comment]
@rmd13 Whoa, I'm surprised restarting fixed it. That error is a known issue with the version of Fiji. One workaround is to delete the file `Fiji.app/jars/FilamentDetector-1.0.0.jar`, then try again. Sorry for the inconvenience; we'll be rolling out a new Fiji release very soon that will address this issue.

**Comment by rmd13** [comment]
I am using an very old Fiji app with ij version 52p(~around 2014), possible thats why restart is OK. 
A difference I can see in Plugins menue is that ~80% plugins is not listed in this menue of the imagej panel (which I downloaded and collected to .\plugins folder during many years, all in Java 6 version), only a few of them can be shown on the list.
Another very usefulthing is that by calling IJ = sj.jimport('ij.?.?'), many classical command inside ij.jar can be called,
