### ISSUE TITLE
help - scifio exception when reading ics file

### ISSUE THREAD

**Issue by drmatthews** [imagej/pyimagej#125]
Thanks for pyimagej!

I am using it in an image processing pipeline where I use it to read FLIM data, saved in ICS format, segment using scikit-image and then pass the result of the segmentation to flimj-ops.

The reading of the ICS was working fine but now is not. I am getting the following exception:

```
io.scif.FormatException: io.scif.FormatException: Cannot discern ICS version
```

I think this stopped after updating my local Fiji installation. I have tried a remote endpoint but I get the same behaviour. The odd thing is that if I started the Fiji application and File --> Open, the images are read as expected. This is what made me decide to post the issue here and not in the SCIFIO repo.

Any ideas?

**Comment by drmatthews** [comment]
Apologies, it was a problem with the file itself.

**Comment by ctrueden** [comment]
@drmatthews Glad to hear you got it sorted! :+1:
