### ISSUE TITLE
Support conversion of `ImgLabeling` objects to/from NumPy arrays

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#127]
And do it how napari does it for its labels layers.

**Comment by ctrueden** [comment]
Also important to be aware of: CellProfiler's [centrosome](https://github.com/CellProfiler/centrosome) has a structured called ijv that is a stack of masks, in order to support overlapping labels. This is probably analogous to the `ImgLabeling` support for multiple labels. We might want to consider conversion to/from the ijv format as an option, too? Although adding a dependency on centrosome would probably not be ideal, nor of use to napari. But I wanted to write about it here before it leaves my brain.

**Comment by imagejan** [comment]
Does napari's labels layer support overlapping labels? Or is the index image (`ImgLabeling#getIndexImg()`) enough?

For the opposite direction (numpy -> RandomAccessibleInterval -> ImgLabeling), see also https://github.com/imagej/imagej-common/pull/93 and https://github.com/imagej/imagej-common/pull/94.

**Comment by gselzer** [comment]
> Does napari's labels layer support overlapping labels?

Not yet. There is an issue (https://github.com/napari/napari/issues/269) and some work started by @0x00b1 (https://github.com/napari/napari/pull/2782)

**Comment by ctrueden** [comment]
> There is an issue (napari/napari#269) and some work started by @0x00b1 (napari/napari#2782)

And as we discussed earlier today, @tomburke-rse also made [pyLabeling](https://github.com/Labelings/pyLabeling), which is probably our best starting point!
