### ISSUE TITLE
Pyimagej support ARM Mac not yet? 

### ISSUE THREAD

**Issue by Jintopia** [imagej/pyimagej#130]
There is a problem with imagej.init 

` ij = imagej.init('/Applications/Fiji.app',headless=False)`

Error code
`WARNING: Not able to assign machine() = arm64 to a cpu value!
         Using cpu = 'i386' instead!
[0.003s][warning][os,thread] Attempt to protect stack guard pages failed (0x00000001696c0000-0x00000001696cc000).
[0.003s][warning][os,thread] Attempt to deallocate stack guard pages failed.`

Pyimagej support ARM Mac not yet?

**Comment by ctrueden** [comment]
I don't have an ARM Mac to test, but I'm curious which layer is failing. PyImageJ is built on scyjava which is built on JPype. Could you please try the following:
```
python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); print(jpype.JClass("java.lang.System").getProperty("java.version")); jpype.shutdownJVM()'
```
and report the output here?

On my linux64 system, I see:
```
True
11.0.9.1-internal
```

You can also try setting the path to your Java installation explicitly; e.g.:
```
$ JAVA_HOME=~/Java/linux64/adopt-14.0.2.12 python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); print(jpype.JClass("java.lang.System").getProperty("java.version")); jpype.shutdownJVM()'
True
14.0.2
```

**Comment by vijay-yelanji** [comment]
any solution for this ?

**Comment by vijay-yelanji** [comment]
on my  mac M1 chip   still getting same error

**Comment by vijay-yelanji** [comment]
on non M1 chip no issue, jpype can load java classes..

**Comment by ctrueden** [comment]
@vijay-yelanji The OP did not respond to my followup questions.

If you respond to my followup questions, perhaps we can get to the bottom of it.

**Comment by vijay-yelanji** [comment]
Hello Curtis ,

Sample Program :
python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); print(jpype.JClass("java.lang.System").getProperty("java.version")); jpype.shutdownJVM()'

**### OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
Killed: 9**

JDK  
venv2) <HOST>:venv2 vijay.yelanji$ java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Zulu 8.66.0.15-CA-macos-aarch64) (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Zulu 8.66.0.15-CA-macos-aarch64) (build 25.352-b08, mixed mode)

venv2) <HOST>:venv2 vijay.yelanji$ uname -a
Darwin <HOST> 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

Any help appreciated ..

Note : The issue is  same for  Pyjnius as well as JPype . But it works fine on intel based Mac

Thanks
Vijay

**Comment by ctrueden** [comment]
@vijay-yelanji I don't have a solid answer, but here are more two things to check:

1. Did you try the JPype one-liner above with OpenJDK 11? How about with OpenJDK 17? These might work better than OpenJDK 8.

2. Did you install your Python environment via conda/mamba? Or via pip? If you are using conda/mamba, try setting up a new environment where you `pip install` JPype, because that will compile it from source, which might work better.

@mkitti Could you possibly spare a few minutes to try out PyImageJ with your Mac M1?

**Comment by vijay-yelanji** [comment]
For our need , I need to use JDK7 .. so I tried only on JDK 7/8.  All I did via pip using virtual environment.

I didn't  try building  JPType . But I can try PyImageJ and get back to you . Will later JDK11 or 17 later to see it is working.

Thank you very much for the response.

**Comment by mkitti** [comment]
```
% python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); sys = jpype.JClass("java.lang.System"); print(sys.getProperty("java.version")); print(sys.getProperty("os.arch")); jpype.shutdownJVM()'

True
17.0.3
aarch64
```

<details>
<summary>Conda Environment</summary>

```
% conda list
# packages in environment at ~/miniforge3-arm64/envs/pyimagej:
#
# Name                    Version                   Build  Channel
aom                       3.5.0                h7ea286d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               hd414afc_3    conda-forge
brotli                    1.0.9                h1c322ee_7    conda-forge
brotli-bin                1.0.9                h1c322ee_7    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-blosc2                  2.4.3                h303ed30_0    conda-forge
ca-certificates           2022.9.24            h4653dfc_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                hd4f5c17_0    conda-forge
charls                    2.3.4                hbdafb3b_0    conda-forge
contourpy                 1.0.5           py310h2887b22_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dav1d                     1.0.0                he4db4b2_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 1.1.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0          py310h8e9501a_0    conda-forge
freetype                  2.12.1               hd633e50_0    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
imagecodecs               2022.9.26       py310hf9f14f2_1    conda-forge
imglyb                    2.0.1              pyh8a188c0_0    conda-forge
ipython                   8.5.0              pyhd1c38e8_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jgo                       1.0.4              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   he4db4b2_2    conda-forge
jpype1                    1.4.0           py310hd23d0e8_0    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4           py310hd23d0e8_0    conda-forge
krb5                      1.19.3               he492e65_0    conda-forge
labeling                  0.1.12             pyhd8ed1ab_1    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.0.6                hbdafb3b_0    conda-forge
libavif                   0.11.0               h3d80962_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1c322ee_7    conda-forge
libbrotlidec              1.0.9                h1c322ee_7    conda-forge
libbrotlienc              1.0.9                h1c322ee_7    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcurl                   7.85.0               h1c293e1_0    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libdeflate                1.14                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libnghttp2                1.47.0               h519802c_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.38               h76d750c_0    conda-forge
libsqlite                 3.39.4               h76d750c_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libtiff                   4.4.0                hfa0b094_4    conda-forge
libwebp-base              1.2.4                h57fd34a_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
matplotlib-base           3.6.1           py310h78c5c2f_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
maven                     3.8.6                hce30654_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.23.4          py310h5d7c261_0    conda-forge
openjdk                   17.0.3               hf913c23_2    conda-forge
openjpeg                  2.5.0                h5d4e404_1    conda-forge
openssl                   3.0.5                h03a7124_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1           py310h2b830bf_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h173adc3_2    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
psutil                    5.9.3           py310h8e9501a_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyimagej                  1.2.1           py310hbe9552e_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.6          hae75cb6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.5             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
scipy                     1.9.3           py310ha0d8a01_0    conda-forge
scyjava                   1.7.0              pyhd8ed1ab_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h39c3846_1    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
tifffile                  2022.10.10         pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
unicodedata2              14.0.0          py310hf8d0d8f_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.10.0          pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zfp                       1.0.0                h7b19444_2    conda-forge
zlib-ng                   2.0.6                he4db4b2_0    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```
</details>

**Comment by mkitti** [comment]
OpenJDK11:

```
% python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); sys = jpype.JClass("java.lang.System"); print(sys.getProperty("java.version")); print(sys.getProperty("os.arch")); jpype.shutdownJVM()'

True
11.0.15
aarch64
```

**Comment by mkitti** [comment]
OpenJDK8:

```
% mamba install openjdk=8.0.312

% python -c 'import jpype; jpype.startJVM(); print(jpype.isJVMStarted()); sys = jpype.JClass("java.lang.System"); print(sys.getProperty("java.version")); print(sys.getProperty("os.arch")); jpype.shutdownJVM()'

OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
OpenJDK 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed.
True
1.8.0_312
aarch64
```

**Comment by mkitti** [comment]
I cannot get `mamba install openjdk=8.0.332` to work.

xref: https://github.com/conda-forge/openjdk-feedstock/issues/109

**Comment by mkitti** [comment]
Other than a few warnings and having to specify openjdk version `8.0.312`, pyimagej seems to work well on ARM Mac.

```python
In [1]: import imagej

In [2]: ij = imagej.init(mode='headless')
OpenJDK 64-Bit Server VM warning: Attempt to protect stack guard pages failed.
OpenJDK 64-Bit Server VM warning: Attempt to deallocate stack guard pages failed.

In [3]: ij.getVersion()
Out[3]: '2.9.0/1.53t'

In [4]: import jpype

In [5]: sys = jpype.JClass("java.lang.System")

In [6]: sys.getProperty("os.name")
Out[6]: 'Mac OS X'

In [7]: sys.getProperty("os.version")
Out[7]: '12.4'

In [9]: sys.getProperty("os.arch")
Out[9]: 'aarch64'

In [10]: sys.getProperty("java.version")
Out[10]: '1.8.0_312'
```

```
% java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)
```

**Comment by vijay-yelanji** [comment]
I tried PyImageJ on Mac M1. Didn't work Got below error
>> import imagej
>>> ij = imagej.init(mode='headless')
Failed to bootstrap the artifact.

Possible solutions:
* Double check the endpoint for correctness (https://search.maven.org/).
* Add needed repositories to ~/.jgorc [repositories] block (see README).
* Try with an explicit version number (release metadata might be wrong).

Full Maven error output:
	[ERROR] [ERROR] Some problems were encountered while processing the POMs:
	[ERROR] Non-resolvable import POM: Failed to resolve version for net.imagej:imagej:pom:RELEASE: Could not find metadata net.imagej:imagej/maven-metadata.xml in local (/Users/vijay.yelanji/.m2/repository) @ line 8, column 29
	[ERROR] 'dependencies.dependency.version' for net.imagej:imagej-legacy:jar is missing. @ line 10, column 254
	[ERROR] The build could not read 1 project -> [Help 1]
	[ERROR]   
	[ERROR]   The project net.imagej-BOOTSTRAPPER:imagej-BOOTSTRAPPER:0 (/Users/vijay.yelanji/.jgo/net.imagej/imagej/RELEASE/bf9da2ebe6c78d8bd105a97ce32adcfe853ce5e97dd621b9e35936d1c6abf90c/pom.xml) has 2 errors
	[ERROR]     Non-resolvable import POM: Failed to resolve version for net.imagej:imagej:pom:RELEASE: Could not find metadata net.imagej:imagej/maven-metadata.xml in local (/Users/vijay.yelanji/.m2/repository) @ line 8, column 29 -> [Help 2]
	[ERROR]     'dependencies.dependency.version' for net.imagej:imagej-legacy:jar is missing. @ line 10, column 254
	[ERROR] 
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR] 
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
	[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


***Invalid Initialization: you may be using primary endpoint that lacks pom-scijava as a parent***
   To keep all Java components at compatible versions we recommend using a primary endpoint with a pom-scijava parent.
   For example, by putting 'net.imagej:imagej' first in your list of endpoints.
   If you are sure you DO NOT want a primary endpoint with a pom-scijava parent, please re-initialize with 'add_legacy=False'.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vijay.yelanji/python/venv2/lib/python3.9/site-packages/imagej/__init__.py", line 1498, in init
    raise RuntimeError("Failed to create a JVM with the requested environment.")
RuntimeError: Failed to create a JVM with the requested environment.

**Comment by vijay-yelanji** [comment]
As of now , I will continue with intel based Mac until I upgrade  to JDK11.. Thank you all your support

**Comment by mkitti** [comment]
@vijay-yelanji  have you tried to install this with conda-forge?

**Comment by vijay-yelanji** [comment]
I didn't install conda.  Will try..

**Comment by vijay-yelanji** [comment]
today I installed JDK 19

Set Envs. and added classpath

JVM_PATH=/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/lib/server/libjvm.dylib
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home


import jpype

#jpype.startJVM(); 

jpype.startJVM(jpype.getDefaultJVMPath(), "-ea", "-Djava.class.path=**my.jar**");

util = jpype.JClass("**MyClass**")

print(util)

Results 

(venv2) vijay.yelanji@HOS % **python jp.py**
<java class 'MyClass'>
True
19.0.1

Thank you all for your support...
