### ISSUE TITLE
Unable to get an image from WindowManager

### ISSUE THREAD

**Issue by patquem** [imagej/pyimagej#131]
Hello,

I have a problem quite similar to #109.

After running a plugin ('VSNR_Macro_2D' in my case), I have 3 images (the input one 'image' + 2 new ones 'Denoised Image', 'Noise'):
`print(WindowManager.getImageTitles())`
>['image', 'Denoised Image', 'Noise']

When I try to send the 'Denoised Image' to python, I have the following error :
```
result = WindowManager.getImage('Denoised Image')
print(result)
result.changes = False
ij.py.synchronize_ij1_to_ij2(result)
arr_res = ij.py.from_java(result)
```
>img["Denoised Image" (-11), 16-bit, 1800x2000x1x1x1]
...
>AttributeError: 'NoneType' object has no attribute 'getProperties'

I have tried to pass the 'Denoise Image' to the active Windows with no more success :
```
win_den = WindowManager.getWindow('Denoised Image')
WindowManager.setCurrentWindow(win_den)
result = WindowManager.getCurrentImage()
...
```
Any idea to fix that ?
Patrick

**Comment by elevans** [comment]
@patquem 

I haven't used the VSNR_Macro_2D before but the object `WindowManager` is returning should be `ij.ImagePlus`. As you are already aware many plugins were not designed to run headlessly and may not work.

Assuming that `WindowManager` is returning an `ImagePlus` object, this should work:

```python
result = WindowManager.getImage('Denoised Image')
result_ds = ij.py.to_dataset(result) # convert from ImagePlus to Dataset
arr_res = ij.py.from_java(results_ds)
```

P.S. You can get to the `WindowManager` easily with `ij.py.window_manager` instead of importing it manually.

**Comment by elevans** [comment]
TODO:
- [ ] Verify that this is a headless issue.
- [ ] Check if headless limitations are clearly documented.

**Comment by hinerm** [comment]
I can confirm that `'VSNR_Macro_2D` works when initializing with `headless=False`. It produces a `Noise` and `Denoised Image` window which are both accessible through pyimagej (e.g. `ij.py.window_manager().getImage('Denoised Image')`)

Closing in favor of #174
