### ISSUE TITLE
Remove me from list of maintainers

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/pyimagej#132]
Hi Curtis @ctrueden ,

would you mind removing me from the list of pyimagej maintainers? Alternatively, tell me how to :-)

![image](https://user-images.githubusercontent.com/12660498/129736852-a222927f-542a-4000-b7d2-cae18f7761dd.png)

Thanks a lot!

Best,
Robert

**Comment by ctrueden** [comment]
@haesleinhuepf Sure, done!

And if you ever want to manage any of your PyPI projects in future, here is how I did it, while logged in to pypi.org:

![pypi-collaborators-pyimagej](https://user-images.githubusercontent.com/556626/129786013-0f5ad7cf-b118-4795-a27c-846da3d007bb.png)

**Comment by haesleinhuepf** [comment]
Thanks Curtis! :-)
