### ISSUE TITLE
loading local imagej + specific imglib

### ISSUE THREAD

**Issue by orena1** [imagej/pyimagej#136]
Is it possible to load a local imagej/fiji together with a specific net.imglib2 version?

I've tried the following and it did not work:
```
import imagej

ij = imagej.init('/home/amsalem/Downloads/Fiji.app/Fiji.app+net.imglib2:imglib2-unsafe:0.4.1',headless=False)
ij.ui().showUI()
```

Thanks

**Comment by imagejan** [comment]
I don't think this is possible. See here for the initialization logic:

https://github.com/imagej/pyimagej/blob/ccdcc0dd82071a83aaa842cdc3ab2d98444658cb/imagej/__init__.py#L142-L146

See here for the different initialization options:

https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md#ways-to-initialize

**Comment by ctrueden** [comment]
It is not possible, but you can instead place the specific JARs you want to use into your local Fiji installation. Be sure to delete or move away any other JARs of the same groupId:artifactId but different version, so that they don't clash.
