### ISSUE TITLE
pyimage's local Fiji panel shows less plugins than directly run Fiji from exe.

### ISSUE THREAD

**Issue by rmd13** [imagej/pyimagej#141]
Hi,
I want to use a plugin in pyimage environment.
I download the plugin ij_ridge_detect-1.4.0 from
https://mvnrepository.com/artifact/de.biomedical-imaging.imagej/ij_ridge_detect/1.4.0
and place it in the plugins folder, and can run it from Fiji executable.

Now I launch pyimagej from the same local Fiji path, but found that the plugins menu only shows very few plugins much less than run from Fiji executable. I also cannot find ij_ridge_detect plugin there.  I also cannot run the command because it says cannot find the plugin.
`        IJ.run(ips_raw_defer_crop_masked, "Ridge Detection", "line_width=3.5 high_contrast=230 low_contrast=87 displayresults add_to_manager method_for_overlap_resolution=NONE sigma=1.51 lower_threshold=3.06 upper_threshold=7.99 minimum_line_length=10 maximum=0");
`

How does this happen? Is there a way to call that plugin?
Thanks.

**Comment by imagejan** [comment]
@rmd13 can you check which version of `imagej-legacy` is in your local Fiji installation?

There was a bug in `imagej-legacy` related to `plugins.config` parsing that was fixed in https://github.com/imagej/imagej-legacy/pull/266 with `imagej-legacy-0.38.0`, see also https://github.com/imagej/pyimagej/issues/129 and https://github.com/imagej/pyimagej/issues/133.

**Comment by ctrueden** [comment]
I believe this was fixed by imagej/imagej-legacy#266 (thanks @hinerm!). Closing for now. @rmd13 Please reopen if you test with a version of imagej-legacy 0.38.0 or newer, and the issue persists. Thanks!

**Comment by rmd13** [comment]
Hi, I found a imagej-legacy-0.3.0.jar inside \jar\ folder.
Shall I only replace the imagej-legacy jar file, or should I reinstall a newest Fiji?
Thank you

**Comment by rmd13** [comment]
I download imagej-legacy-0.38.0.jar from
https://mvnrepository.com/artifact/net.imagej/imagej-legacy/0.38.0
and replaced with the original one, then test in Imagepy
Now I can see more menus! Great!

**Comment by ctrueden** [comment]
@rmd13 Glad to hear!

For what it's worth, just running the ImageJ Updater should dole out a new-enough imagej-legacy at this point. But glad you got it working to drop in the file manually.
