### ISSUE TITLE
Consider setting working directory on startup

### ISSUE THREAD

**Issue by hinerm** [imagej/pyimagej#150]
[Some plugins](https://github.com/imagej/pyimagej/issues/143#issuecomment-968892406) may have been written on the assumption that the current working directory *is* the `Fiji.app` directory.

These can always be worked around by starting the python interpreter in the `Fiji.app` directory or adding to a python script:
```
import os
os.chdir('/path/to/Fiji.app')
```

It might save users some headaches/troubleshooting if we automatically called `chdir` on `init`. But it could also be unexpected and cause *other* problems. Also it may not work anyways when using a `jgo`-initialized ImageJ due to the flattened directory structure.

So I think our choices are:
1. Document in [Troubleshooting](https://github.com/imagej/pyimagej/blob/1.0.2/doc/Troubleshooting.md)
2. Just set the CWD when initializing with a local `Fiji.app`
3. Always set the CWD when initializing, whether local or via `jgo`

**Comment by ctrueden** [comment]
Since we opted not to set JAVA_HOME automatically... for consistency I'd favor not changing this environmental characteristic either, but rather document that it needs to be done for certain plugins to behave as expected. Option (1).

**Comment by jhnnsrs** [comment]
Hello! First of all thanks for this package :) Really a great project !
I would like to reopen this issue as it just caused a lot of headache for me ;)
I believe that changing os.path within an init function is unexpected behaviour and could potentially
lead to sever bugs like unexpectedly deleting directories (e.g during script cleanup), path traversal
attacks. Maybe enabling it through specific call or setting init parameter to disable the behaviour, might be a solution?

**Comment by ctrueden** [comment]
@jhnnsrs Sorry to hear that the setting of CWD caused a headache for you!

@hinerm Do you know if any other plugins besides Action Bar have this CWD == Fiji.app assumption? If not, my vote would be to revert this behavior, not change the CWD, and instead fix the Action Bar code. But if there are also other plugins that make this assumption, then it becomes more involved to fix them all. What do you think?

**Comment by hinerm** [comment]
>Do you know if any other plugins besides Action Bar have this CWD == Fiji.app assumption? If not, my vote would be to revert this behavior, not change the CWD, and instead fix the Action Bar code.

I am not aware of any off the top of my head. I would be fine with reverting and noting the work-around in Troubleshooting. I don't think we need to change Action Bar; I am not able to locate a GitHub repo for it.

Sound good or do you think we should do something more with Action bar?

**Comment by ctrueden** [comment]
https://github.com/mutterer/ActionBar ? But it hasn't been updated since 2017. @mutterer Is there a newer version somewhere?
