### ISSUE TITLE
How to properly reset pyimagej in a server environement

### ISSUE THREAD

**Issue by oeway** [imagej/pyimagej#154]
Hi, I would like to run pyimagej on the server side and for each user session we would like to do a reset. I wonder what's the best way to do it.

I basically queue the request of users, so at one point each pyimagej process will serve only one user at a time, no concurrency needed.

@ctrueden mentioned that I could do `ij.displose()` then `ij.init()`, but also mentioned that "But if someone wrote Java code that creates other windows, it wouldn't dispose them.". I am also wondering how often a fiji plugin will create windows that ij.dispose cannot close. Is there a more reliable solution?

**Comment by elevans** [comment]
Hi @oeway,

I'm not sure how often a Fiji plugin would try to create windows outside of `ij.dispose()` scope. We recently made changes to how PyImageJ shuts down. Specifically we made a change to ensure all windows are disposed as we found on Windows OS some hidden windows (???) were being generated and the `ij.dispose()` call was insufficient. Here's the relevant commit: https://github.com/scijava/scyjava/commit/c5d8ac1a10e527db392d02a1ffef0f29fb5c021f

Perhaps you can include something similar in a reset/clean up routine.

**Comment by oeway** [comment]
hi, Great! Thanks for the tip, I will give it a try.

**Comment by ctrueden** [comment]
As of this writing, PyImageJ's supporting scyjava library [disposes all AWT windows as part of JVM shutdown](https://github.com/scijava/scyjava/blob/1.7.0/src/scyjava/_java.py#L263-L267) only when the AWT subsystem is already active. This lets Java+Python shut down cleanly in both headful and headless scenarios.

@oeway Not sure if your code would benefit from such "AWT detection" but if so, you might find [our hack](https://github.com/scijava/scyjava/blob/1.7.0/src/scyjava/_java.py#L294-L309) helpful.

@oeway Are you still having problems along these lines? Or can this issue be closed now?

**Comment by oeway** [comment]
I haven't tested the new version, but please feel free to close the issue and we can reopen it.
