### ISSUE TITLE
Support conversion of `RealType`s to Python numbers

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#162]
While we can convert images of `RealType`s from java to python, we cannot seem to convert individual `RealType`s.

```python
import imagej
from scyjava import jimport

ij = imagej.init()

DoubleType = jimport('net.imglib2.type.numeric.real.DoubleType')
d = DoubleType(1)

ij.py.from_java(d) # Fails here!
```

We get the following Error:
```
TypeError: Unsupported data type: <java class 'net.imglib2.type.numeric.real.DoubleType'>
```

In most cases, this is quite trivial, as when we have a `RealType` we could just call `ij.py.from_java(d.getRealDouble())`. But, when we do not know whether the data passed to `from_java` is a `RealType` (as is the case in the napari-imagej plugin), this would involve case logic. We *could* add that case logic, but it seems like a pretty easy fix in `from_java`.

**Comment by imagejan** [comment]
*Side note*: we're not even supporting handling outputs of `RealType` currently in Fiji, unrelated to converting to Python.

See https://github.com/imagej/imagej-common/issues/80 and https://github.com/imagej/imagej-common/pull/82.
