### ISSUE TITLE
Any toy examples on "Analyze Particles"?

### ISSUE THREAD

**Issue by WT215** [imagej/pyimagej#164]
Hi,

I would like to apply "Analyze Particles" function on a numpy array (an image with several dots), and I would like to obtain the coordinates of each dot.

Is it possible to do that?

BTW, how do we find all available function names like the function for doing threshold?

Many thanks!

**Comment by ctrueden** [comment]
@WT215 Sorry for the long delay in reply! There are two examples of using Analyze Particles with PyImageJ now:

* [8.2 Example 2: Extract a slice and run “Analyze Particles…”](https://pyimagej.readthedocs.io/en/latest/08-Discover-and-run-ImageJ-commands.html#example-2-extract-a-slice-and-run-analyze-particles)
* [Puncta Segmentation](https://pyimagej.readthedocs.io/en/latest/Puncta-Segmentation.html)

Maybe too late to help you, but hopefully still useful for anyone else with the same questions!

> BTW, how do we find all available function names like the function for doing threshold?

ImageJ has a lot of commands in its menu structure, and it is extensible with plugins, so an exhaustive list would be a lot. But one easy trick is to search for things via the ImageJ2 search bar, which available in Fiji. Type in an operation of interest (e.g. `thresh`), and see which commands come back. If you start the [Macro Recorder](https://imagej.net/scripting/macro#the-recorder) before running a command, and change it to Python mode, then run the commands you want, the Recorder will have generated syntax which is typically very close or identical to what you would write using PyImageJ.

Happy to help further if you write questions on forum.image.sc with tag `pyimagej`!
