### ISSUE TITLE
Python 2 vs. 3

### ISSUE THREAD

**Issue by MitchChild** [imagej/pyimagej#166]
I'm curious if this is only capable of running on python 2? I would like to be able to run things on python 3. Any help is greatly appreciated

**Comment by ctrueden** [comment]
@MitchChild PyImageJ requires Python 3.6 or later. I just pushed c24c5fc9e085f7ece415bf532d5d4cf8d155ae09 which enforces this in the `setup.py`.

Could you elaborate on the problems you are encountering when using it with Python 3?
