### ISSUE TITLE
Document CellProfiler+ImageJ mechanism(s) in the right places

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#169]
Somewhere, we need to write up how to use RunImageJScript. Ideally, there would be a page on the cellprofiler.org documenting how people can do CP+ImageJ, be it RunImageJScript, RunImageJMacro, or whatever other options exist.

We shouldupdate https://imagej.net/software/cellprofiler with information about PyImageJ-based integration, and link off to the CP-side docs.

**Comment by hinerm** [comment]
Closed in https://github.com/imagej/imagej.github.io/commit/fb5180fb98ca7e4849587dc80fd9ec8316302b46
