### ISSUE TITLE
Flesh out Headless guide into a notebook

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#174]
Rework `doc/Headless.md` into `doc/Headless.ipynb`.

* What is headless mode, and why you would want it.
* Limitations of headless mode
* How to start PyImageJ headless
* If you need to run a GUI without a screen, you can use xvfb. See Xvfb.md.

Start from [NicolasCristini's notebook](https://github.com/NicolasCristini/ImageJ-Processing-Assistant-Notebook) and also [Curtis's headless experimental notebook](https://github.com/imagej/i2k-2020-pyimagej/commit/56199778023465a95c595dbcc06eacf3ad5c0681), and figure out what can and can't be done
- update Troubleshooting with specifics as needed
- update headless notebook ideally to show what DOES work
- as time allows, dig in imagej-legacy regarding WHY opening an image from a macro works to register it headless -- ideally we can just have a more general way to register ImagePlus objects

**Comment by elevans** [comment]
We're closing this issue because this will now be addressed in #205. The I2K 2022 content will address the listed goals.
