### ISSUE TITLE
Split PyImageJ-Tutorial and PyImageJ-Code-Snippets into individual tutorial sections

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#175]
@elevans and I started splitting up the PyImageJ-Tutorial notebook into pieces. Here is the new structure (currently on the `docs` branch), along with what still needs to be done:

1. Starting-PyImageJ
2. Opening-and-Displaying-Images
    * merge in stuff from code snippets
3. Sending-Data-to-Java: ij.py.to_java
    * roll in conversion table and explanation from Usage.md
4. Retrieving-Data-from-Java: ij.py.from_java
5. Working-with-Images
    * roll in ij.py convenience methods
    * roll in Code-Snippets channel manipulation
6. Running-Macros-Scripts-and-Plugins
    * roll in "Using original ImageJ macros..." section from Usage.md
7. Visualizing-Large-Images
8. Troubleshooting
    * add note to top linking to Troubleshooting.md

Also ensure that:

- each tutorial runs standalone (including an `imagej.init('2.3.0')` cell at the top of each)
- `headless=True` updated to `mode='headless'` everywhere; ensure everything else still runs
- we update the Working-with-Images notebook's `ij.py` functions info to reflect current structure as we relocate those functions
- migrate useful details from the [6-ImageJ-with-Python-Kernel](https://github.com/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb) notebook of the imagej/tutorials repository

Finally, we want to **consolidate and migrate `Usage.md` into the tutorial notebooks**, since there is a lot of the same information there, but also some useful details not currently present in the notebooks.

**Comment by ctrueden** [comment]
@elevans The split is done on the master branch now. You just need to go into each tutorial notebook and clean up the introductions, and fix any problems executing them fresh start-to-finish.

**Comment by elevans** [comment]
All these tasks have been completed (yay!). They are part of PyImageJ 1.1.1 1145321594bfa4463fab2e61882c582c77cd2a18.
