### ISSUE TITLE
PyPi documentation links aren't working

### ISSUE THREAD

**Issue by hinerm** [imagej/pyimagej#177]
On the [ImageJ wiki](https://imagej.net/scripting/pyimagej) we point to the [pypi](https://pypi.org/project/pyimagej) site for pyimagej. Unfortunately all the relative links in our [README.md](https://github.com/imagej/pyimagej/blob/master/README.md) do not work on the pypi description. This leaves us with 1) a broken pypi description and 2) limited linkage to the actual working documentation on GitHub.

I suggest making our pypi project descriptions more like Jpype, for example, with minimal info that links off to source/documentation:
![image](https://user-images.githubusercontent.com/1123809/154756441-44416c28-7769-4ad2-8fba-56986ac44058.png)

**Comment by ctrueden** [comment]
@hinerm With @elevans, I had implemented a fix for this issue, inside the `setup.py` (look at the `.replace` lines). I do not think we need to change the README drastically—just figure out why the PyPI document has not been tweaked as intended.

**Comment by hinerm** [comment]
This is already fixed (in da9330a1ab69d6877b95dcef8fee8915eeab6e34) and it's just that we haven't had a release since then
