### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by LisaVdB** [imagej/pyimagej#180]
Hi, it's more a question than an issue. We used the pyamagej package in an application that we are submitting to a journal. How should we cite pyimagej? Thank you! Lisa

**Comment by elevans** [comment]
We are in the process of submitting a publication for PyImageJ. In the meantime you can use the zenodo reference. Its on the PyImageJ page on the [imagej.net wiki](https://imagej.net/scripting/pyimagej#citing).

**Comment by LisaVdB** [comment]
Great ! Our paper is still a long way from actual publishing so perhaps by that time, we can cite your publication :-)
