### ISSUE TITLE
Add -Djava.net.useSystemProxies=true tip to docs about proxy configuration

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#183]
It's simpler than our current recommendations. See also https://github.com/imagej/pyimagej/issues/121#issuecomment-1089409309

**Comment by gselzer** [comment]
@ctrueden is this [done](https://github.com/imagej/pyimagej/blob/master/doc/Troubleshooting.md#could-not-transfer-artifact)?

**Comment by ctrueden** [comment]
Yep, looks like this was resolved with 3697eb31d2d0ccf8588bfaca1e65a450669bec54.
