### ISSUE TITLE
Make doc/Troubleshooting.md less scary and add a Debugging Tips section

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#188]
`doc/Troubleshooting.md` should be more approachable and useful. We know of a lot of good ways to debug this code, and they should be better documented.

This issue was spurred by @ctrueden's comment [here](https://github.com/imagej/pyimagej/commit/a29df7f6f090591cab65dc98faf863c956db9cde#diff-c6150c41536c301d598e0adf013f6e23fb595f1281fe3ea653635de9e22642ebR89)

**Comment by ctrueden** [comment]
I added a "doctor" to make troubleshooting easier (added to Troubleshooting doc as of ec5b7b7996993d84477d011c11f066c0992b0181), as well as a table of contents (e93876a15fd9d3f44ce8bd2ea0eee12be53c4100), so I'm going to call this issue resolved. Over time, we can keep expanding the doctor to cover new problems people report.
