### ISSUE TITLE
Converting between xarray and dataset should preserve image name

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#198]
The `name` property of `DataArray` matches up with `getName()` of `Dataset` and `ImgPlus`.

**Comment by thewtex** [comment]
Hi Curtis! I also ran into this here: https://github.com/spatial-image/spatial-image-multiscale/pull/23

Additional note -- it was helpful to convert `getName()` from a Java String object to a Python string with `str` so it could be serialized to Zarr:

```
# The DataArray name needs to be set
image_da.name = str(image.getName())
```

**Comment by ctrueden** [comment]
Thanks @thewtex. I commented on your PR. I also filed #200 here to cover the conversion issue leading to serialization woes.
