### ISSUE TITLE
Improve type coercion somehow

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#2]
```python
>>> img = io.imread('http://samples.fiji.sc/_malaria_parasites.tif')
>>> import numpy as np
>>> img = np.mean(img, axis=2)
>>> vessels = np.zeros(img.shape, dtype=img.dtype)
>>> ij.op().filter().frangiVesselness(imglyb.to_imglib(vessels), imglyb.to_imglib(img), [1, 1], 20)
<net.imglib2.RandomAccessibleInterval at 0x10b379048 jclass=net/imglib2/RandomAccessibleInterval jself=<LocalRef obj=0x7f8a3ec44e08 at 0x136257cb0>>
>>> ij.scifio().datasetIO().save(imglyb.to_imglib(vessels), 'out.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius/jnius_export_class.pxi", line 906, in jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:29616)
  File "jnius/jnius_export_class.pxi", line 632, in jnius.JavaMethod.__call__ (jnius/jnius.c:25965)
  File "jnius/jnius_conversion.pxi", line 68, in jnius.populate_args (jnius/jnius.c:8922)
  File "jnius/jnius_utils.pxi", line 207, in jnius.check_assignable_from (jnius/jnius.c:6212)
jnius.JavaException: Invalid instance of 'net/imglib2/python/ReferenceGuardingRandomAccessibleInterval' passed for a 'net/imagej/Dataset'
```

**Comment by hanslovsky** [comment]
`DatasetIOService` does not have a method `DatasetIOService.save( RandomAccessibleInterval, String )`, does it? The only way to make this work would be to add (on the python side) a method like `imagej.to_dataset` that accepts
 - `numpy.ndarray`, or
 - `RandomAccessibleInterval`

and returns a `Dataset`.
Is that what you have in mind?

**Comment by ctrueden** [comment]
I think what I meant when I filed this issue is that the pyjnius objects are statically typed like Java. So e.g. if a method return a `java.util.Collection<String>`, even though in practice the returned object will be some concrete type such as `java.util.ArrayList<String>`, you won't be able to pass that object to another function requiring e.g. a `java.util.List<E>`, unless you cast the object with `myListProcessingFunction(jnius.cast(List, my_collection))`. This is consistent with how Java's static typing works (i.e., in Java you'd need to write `myListProcessingFunction((List) my_collection)`), but is inconsistent with Python's less strict typing approach.

That said, my example above does not illustrate this issue well, since as @hanslovsky points out, the `DatasetIOService.save` method does not accept any old RAI.

**Comment by mpinkert** [comment]
I've been trying to write a helper function for saving a numpy array through ImageJ, and I think I've also hit upon this issue.  The ```imglyb.to_imglib``` function, and correspondingly our new ```ij.py.to_java``` function, returns a ```net/imglib2/python/ReferenceGuardingRandomAccessibleInterval``` class.  So far I haven't been able to save it using ```ij.io.save()``` or the corresponding scifio IO. 

Casting it to ```net.imglib2.img.Img``` makes the command do nothing, while casting to ```net.imagej.DefaultDataset``` throws this error: ```java.lang.IncompatibleClassChangeError```

I was able to save an ImgPlus the ```ij.IJ.save()```.  Opening an image in IJ2, which gave a `net.imageJ.DefaultDataset`, and saving it with ```ij.io().save()``` did work though.

**Comment by ctrueden** [comment]
@mpinkert You can use the `DatasetService` to turn a RAI into a Dataset:
```python
from skimage import data
coins = data.coins()
java_coins = ij.py.to_java(coins)
dataset = ij.dataset().create(java_coins)
ij.scifio().datasetIO().save(dataset, '/Users/curtis/Desktop/coins.png')
```

**Comment by mpinkert** [comment]
@ctrueden I just tested that out - I saw two possible pain points.

1.) Python generated numpy arrays hit pixel type problems.  For example, trying to pass a double gives big errors.  With tifs, ImageJ cannot open the result because `Unsupported BitsPerSample: 64`.  With .pngs, the data doesn't save in the first place due to `Unsupported image type 'double'`.  Example:
```python
from pathlib import Path

img = numpy.zeros([512, 512])
jimg = ij.py.to_java(img)
jdataset = ij.dataset().create(jimg)
jpath = str(Path(Path.home(), 'documents', 'test.tif'))
ij.io().save(jdataset, jpath)
```

You can get around this by specifying an appropriate datatype using `img.astype()`, but we should probably discuss if we want the user to specify this, or if we want to force it into an appropriate type when they pass it in.  


1.) Color images are not converted properly.  Numpy is normally reverse indexed, e.g. [z, y, x].  However, for RGB it is [y, x, C].  Turning it into a dataset makes it save as a 3 column / x row / y slice image.  Fixing the index order is easy, but the image is still saved as a 3D image instead of RGB.  Is there an easy way to specify that the dataset should be saved as RGB?  
```python
from pathlib import Path
from skimage import io

url = 'https://github.com/hanslovsky/imglyb-examples/raw/master/resources/butterfly_small.jpg'
img = io.imread(url)
jimg = ij.py.to_java(img)
jdataset = ij.dataset().create(jimg)
jpath = str(Path(Path.home(), 'documents', 'test.tif'))
ij.io().save(jdataset, jpath)
```

**Comment by mpinkert** [comment]
@ctrueden 

Problem 1, the numpy type errors, occurs both ways.  Converting an 8-bit image to a `ndarray` makes it `dtype('float64')`.  This is a memory issue, and also a problem for RGB images with matplotlib, as matplotlib only plots `int8` or dtype in range [0, 1]

Problem 2 is now part of issue #17.

**Comment by ctrueden** [comment]
Four things being discussed here:

1. The pixel type issue with writing float64 using SCIFIO. It's true that float64 TIFFs are not super compatible with things, including ImageJ1. And you cannot write float64 PNGs. But this issue is unrelated to the issue at hand here.

2. Color image conversion is another separate issue; see #17 for now to track that.

3. Static typing in Python is counterintuitive to Python programmers, who expect dynamic typing. But that's just how pyjnius is. We don't have the bandwidth to change that.

4. Automagical conversion between Python and Java would be amazing, especially when passing a Python object to a Java method call e.g. `WindowManager.setTempCurrentImage(my_numpy_array)` that could implicitly expand to `WindowManager.setTempCurrentImage(ij.py.to_java(my_numpy_array))`. But this is tricky for a couple of reasons: A) how to inject the `ij` context?; B) how to alter pyjnius's Java method invocation behavior at a low level like that?. For now, we'll not attempt to make this work.
