### ISSUE TITLE
Add binder badge

### ISSUE THREAD

**Issue by hadim** [imagej/pyimagej#20]
And also the `environment.yml` to install the dependencies.

**Comment by ctrueden** [comment]
I did put an `environment.yml` already! Did I do it wrong?

**Comment by ctrueden** [comment]
Are there going to be notebooks in here that we want to run in Binder? I thought not?

**Comment by hadim** [comment]
You're right the tutorials repo might be a better place for it: https://github.com/imagej/tutorials
