### ISSUE TITLE
Trouble running macros (newbie mistake?)

### ISSUE THREAD

**Issue by andreasala98** [imagej/pyimagej#201]
Hi everyone,
I am facing some troubles with running macros through pyimagej.

I need to run a rather complex macro, that calls functions inside and basically builds a .nii (Nifty) file out of dicom slices.
However, I am facing some errors when I try to run the very simple macro:
```python
import imagej

 ij = imagej.init()
 print(f"ImageJ2 version: {ij.getVersion()}")

 macro = """ print("Hello world"); """
 result = ij.py.run_macro('IJ1 Macro', macro)

```

but I get the following error log:
```
ImageJ2 version: 2.5.0/1.53r (this is correctly printed)
Operating in headless mode - the original ImageJ will have limited functionality.
[ERROR] Ignoring extraneous argument: print("Hello world");
[java.lang.Enum.toString] [ERROR] Ignoring extraneous argument: print("Hello world");
Macro Error: Undefined variable in line 1
 
var ; initializeSciJavaParameters ( ) ; <IJ1> Macro [java.lang.Enum.toString] Macro Error: Undefined variable in line 1
 
var ; initializeSciJavaParameters ( ) ; <IJ1> Macro 
[java.lang.Enum.toString] 
```

Can anyone tell me if I am missing something very basic? Thanks!

**Comment by ctrueden** [comment]
@andreasala98 Ahh, I found your post on the forum! [This one](https://forum.image.sc/t/running-complex-macros-in-pyimagej/67190). I will answer there. :smile:
