### ISSUE TITLE
Incorporate I2K 2022 PyImageJ workshop notebook into docs

### ISSUE THREAD

**Issue by ctrueden** [imagej/pyimagej#205]
The [I2K 2022 PyImageJ workshop](https://github.com/imagej/i2k-2022-pyimagej) contains a notebook with new useful material. We should, at minimum, link to it from the PyImageJ doc README. And perhaps we should do more, incorporating elements of it into the primary documentation? The workshop is static and won't change in future, but moving the useful elements into the PyImageJ core docs will keep them more accessible and maintained.

**Comment by elevans** [comment]
Yes this has been completed! The I2k 2022 PyImageJ workshop notebook has been merged into our sphinx documentation scheme which enables us to build our ReadTheDocs site. You can find the jupyter notebooks at https://pyimagej.readthedocs.io/en/latest/notebooks.html.
