### ISSUE TITLE
Where are the sample images located in the tutorial?

### ISSUE THREAD

**Issue by phsamuel** [imagej/pyimagej#212]
I try to follow the [tutorial](https://pyimagej.readthedocs.io/en/latest/2-Working-with-Java-classes-and-Python.html#importing-java-classes-into-python) but am not sure where the sample images (such as 'sample-data/test_image.tif') are located at. Thanks!

**Comment by ctrueden** [comment]
@phsamuel They are [here](https://github.com/imagej/pyimagej/tree/master/doc/sample-data) in this repository! 😄

@elevans Shall we add such a link explicitly from the tutorials that use these sample images?

**Comment by phsamuel** [comment]
Thanks! A link would be helpful for the documents at
https://pyimagej.readthedocs.io/en/latest/. Even now it seems obvious that
I should have tried to dig into the github site. :)

**Comment by elevans** [comment]
Absolutely! I'll add those in where necessary :D.

**Comment by elevans** [comment]
Sorry this took awhile, I got side tracked. I added links to the `doc/sample-data` directory of the repo the appropriate notebooks (1c18893b57a6e02bda35537d5f3efbf1e7c7d223). The PyImageJ read the docs site is up to date :+1: .
