### ISSUE TITLE
RuntimeError: Failed to create a JVM with the requested environment. PyImageJ in Colab

### ISSUE THREAD

**Issue by diegosancarmen** [imagej/pyimagej#217]
Running into this error when I follow [these instructions](https://forum.image.sc/t/pyimagej-on-google-colab/32804).

```
ERROR:jgo:Failed to bootstrap the artifact.
ERROR:jgo:
ERROR:jgo:Possible solutions:
ERROR:jgo:* Double check the endpoint for correctness (https://search.maven.org/).
ERROR:jgo:* Add needed repositories to ~/.jgorc [repositories] block (see README).
ERROR:jgo:* Try with an explicit version number (release metadata might be wrong).
ERROR:jgo:
ERROR:jgo:Full Maven error output:
ERROR:jgo:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-1b9abd470bea>](https://localhost:8080/#) in <module>()
      1 import imagej
----> 2 ij = imagej.init()
      3 print(ij.getVersion())

[/usr/local/lib/python3.7/dist-packages/imagej/__init__.py](https://localhost:8080/#) in init(ij_dir_or_version_or_endpoint, mode, add_legacy, headless)
   1496         success = _create_jvm(ij_dir_or_version_or_endpoint, mode, add_legacy)
   1497         if not success:
-> 1498             raise RuntimeError("Failed to create a JVM with the requested environment.")
   1499 
   1500     if mode == Mode.GUI:

RuntimeError: Failed to create a JVM with the requested environment.
```

Also, could someone outline the steps I need to take in order to run the equivalent code for `Image --> Adjust --> Color Threshold --> LAB` using the ImageJ GUI?  I'm trying to run ImageJ on a Colab notebook and do some very basic analysis but I don't have any idea where to start (brand new ImageJ user).

**Comment by diegosancarmen** [comment]
Not sure what happened but when I restarted the Runtime and then ran everything again it worked.

**Comment by ctrueden** [comment]
> Also, could someone outline the steps I need to take in order to run the equivalent code for Image --> Adjust --> Color Threshold --> LAB using the ImageJ GUI?

In general, you can launch the [macro recorder](https://imagej.net/scripting/macro#the-recorder) in JavaScript mode, run the command(s) you want in the ImageJ GUI, and then take the code generated in the Recorder window and adapt it to Python. However, the Color Threshold command is a bit strange, not too easy to use programmatically. I tried briefly to record the command selecting Lab mode, and got an exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Histogram is null
	at ij.process.AutoThresholder.getThreshold(AutoThresholder.java:44)
	at ij.process.AutoThresholder.getThreshold(AutoThresholder.java:77)
	at ij.plugin.frame.ColorThresholder.autoSetThreshold(ColorThresholder.java:1004)
	at ij.plugin.frame.ColorThresholder.itemStateChanged(ColorThresholder.java:530)
```

> I'm trying to run ImageJ on a Colab notebook and do some very basic analysis but I don't have any idea where to start (brand new ImageJ user).

There are lots of ways of doing things in Python in a notebook. Try posting on forum.image.sc in the Image Analysis category asking for help, including a representative image and brief explanation of what you are trying to do, and you will get more suggestions using various toolkits accessible from Python.

**Comment by diegosancarmen** [comment]
@ctrueden Thanks for the guidance on using Macro.  I'm running into another problem when importing ImageJ:

```
import imagej;
ij = imagej.init(); 
print(ij.getVersion())
-----
2.5.0/Inactive
```
Again, I'm following the above link from forum.image.sc.  Not sure what I'm doing wrong, could you point it out?

**Comment by ctrueden** [comment]
Sorry to drop the ball on this thread, @diegosancarmen. The "2.5.0/Inactive" version happens when you already have an initialized ImageJ2 gateway within the same Python runtime:
* If you are using Jupyter, restart the kernel and rerun the `imagej.init` cell.
* If you have a standalone Python program, ensure you are calling `imagej.init` only once.

Hope that helps!
