### ISSUE TITLE
Is it possible to use ThunderSTORM plugin with pyimageJ?

### ISSUE THREAD

**Issue by tornikepirveli** [imagej/pyimagej#223]
I am trying to automate some of the ThunderSTORM plugin functionality within python, I thought using pyimagej would be great fit for it but I failed to integrate it. I tried running macro scripts on imagej windows application, I recorded them and tried to replicate them in pyimagej, but I got stuck. I don’t know if I am doing something wrong or is ThunderSTORM is unrecordable within imagej, but on a second thought when I run it within imagej generated script it replicates the result.

I would appreciate any tips and help for this issue.

here is the code I try to run:

```
image = ij.IJ.openImage("YFP data 3.tif")
ij.py.run_macro("""run(image, “Run analysis”, “filter=[Wavelet filter (B-Spline)] scale=2.0 order=3 detector=[Local maximum] connectivity=8-neighbourhood threshold=std(Wave.F1) estimator=[PSF: Integrated Gaussian] sigma=1.6 fitradius=3 method=[Weighted Least squares] full_image_fitting=false mfaenabled=false renderer=[Averaged shifted histograms] magnification=5.0 colorizez=false threed=false shifts=2 repaint=50""")
```

And this is the error I get:

```
Error:Undefined variable in line 1:

var ; initializeSciJavaParameters ( ) ; run ( , “Run analysis” , "filter=[Wavelet filter (B-Spline)] scale=2.0 …
```

I believe I have correctly imported all pyimagej dependencies and image opening line works properly, but you are welcome to recommend any new approaches.

**Comment by ctrueden** [comment]
I just noticed this issue, after replying to a [related forum post](https://forum.image.sc/t/using-the-thunderstorm-plugin-with-pyimagej/72206).

@tornikepirveli It looks like your code got some smart quotes (`“` and `”`) mixed into it. Be sure you to use only ASCII `"` quote symbols in computer code.
