### ISSUE TITLE
Using function constructed with pyimagej inside for loop fails

### ISSUE THREAD

**Issue by brunocalet** [imagej/pyimagej#230]
Here's a minimal reproducible example. I have a main.py file with the `showImp()` function and an empty \_\_init\_\_.py file in the same folder as main.py.

`main.py`

```python

import imagej

def showImp (sampleImage):
    # Initialize ImageJ2
    ij = imagej.init()
  
    # Open image and convert from Dataset to ImagePlus
    img = ij.io().open(sampleImage)
    imp = ij.py.to_imageplus(img)
    
    # Show the imp image
    ij.py.show(imp)
    imp.close()

```

When I try to use `showImp()` function inside `analysis.py` file (shown below) everything works fine.

`analysis.py`
```python

from main import analyzeParticles

showImp("sample1.jpg")

```

However, when I try to use the same `showImp()` function for the analysis of multiple images inside a for loop like this I get the error shown below:

`analysis.py`

```python

from main import analyzeParticles

for i in range(1, 21):
    showImp(f"sample{i}.jpg")

```

**Error:**

    Traceback (most recent call last):
      File "/mnt/DataDisk/analysis.py", line 4, in 
    <module>
        showImp(f"sample{i}.jpg", scale=scale)
      File "/mnt/DataDisk/main.py", line 9, in showImp
        imp = ij.py.to_imageplus(img)
      File "/home/conda/envs/pyimagej/lib/python3.10/site-packages/imagej/__init__.py", line 602, in to_imageplus
        self._ij._check_legacy_active("Conversion to ImagePlus is not supported.")
      File "/home/conda/envs/pyimagej/lib/python3.10/site-packages/imagej/__init__.py", line 1106, in _check_legacy_active
        raise ImportError(
    ImportError: The original ImageJ is not available in this environment. Conversion to ImagePlus is not supported. See:  
    https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md

**Comment by NicoKiaru** [comment]
@brunocalet 

` ij = imagej.init() ` is located within the loop, which means, if I understand correctly, that you are trying to initialize ImageJ as many times as the number of images you try to open.

Can you try to remove the ij initialisation it from within the showImp function, and pass ij as an argument of your function ?

**Comment by brunocalet** [comment]
That works perfectly. Thanks!
