### ISSUE TITLE
colour deconvolution

### ISSUE THREAD

**Issue by HeChengHui** [imagej/pyimagej#241]
Is there a way to do colour deconvolution using this library? i don't see any mention in code or documentation.

**Comment by elevans** [comment]
Hi @HeChengHui. PyImageJ is a library for Python/ImageJ integration and does not provide any new analysis features to the ImageJ/Fiji platform. You can do color deconvolution in ImageJ without PyImageJ. See [this](https://imagej.net/plugins/colour-deconvolution) ImageJ wiki link for more info. If you'd like some help doing color decovolution analysis please checkout the [image.sc forum](https://forum.image.sc/).

I just did a quick search on the forum and found this post which might be helpful:
[Color deconvolution implementations & best practice](https://forum.image.sc/t/color-deconvolution-implementations-best-practice/38725/5)
