### ISSUE TITLE
Proper way of loading macro scripts

### ISSUE THREAD

**Issue by jackyko1991** [imagej/pyimagej#246]
Hi pyimagej developers,

I am trying to integrate TrackMate with my python image analysis workflow, and finding pyimagej is the optimal solution to the Fiji macro.

However after checking the documentation, we have to explicitly include the scripts in `ij.py.run_macro` function:
``` python
macro = """
#@ String name
#@ int age
#@ String city
#@output Object greeting
greeting = "Hello " + name + ". You are " + age + " years old, and live in " + city + "."
"""

args = {
    'name': 'Chuckles',
    'age': 13,
    'city': 'nowhere'
}

result = ij.py.run_macro(macro, args)
print(result.getOutput('greeting'))
```

or running with `ij.py.run_script`:
```python
language_extension = 'ijm'
result_script = ij.py.run_script(language_extension, macro, args)
print(result_script.getOutput('greeting'))
```

In TrackMate I have prepared the macro in [jython](https://github.com/trackmate-sc/TrackMate/blob/f2ecfddd3ca514fb1573a3d408f01f234a81b1a5/scripts/ExampleScript_1.py) or [groovy](https://github.com/trackmate-sc/TrackMate/blob/f2ecfddd3ca514fb1573a3d408f01f234a81b1a5/scripts/Run_TrackMate_Headless.groovy). 

What is the proper extension for these two languages?

Can we load the script from `ExampleScript_1.py` or `Run_TrackMate_Headless.groovy` without pasting it inline?

Also if we have converted the image to ImagePlus format in pyimagej, can we pass the image to macro scripts through `args`? If so how can we call the passed image file in the the jython?

**Comment by ctrueden** [comment]
> What is the proper extension for these two languages?

```groovy
#@ ScriptService ss
ss.getLanguages().forEach { println("${it}: ${it.getExtensions()}") }
```
```
Groovy: [groovy]
BeanShell: [bsh]
Clojure: [clj]
ImageJ Macro: [ijm]
Java: [java]
JavaScript: [js]
Python: [py]
R: [R, r, S, s]
Ruby: [rb]
Scala: [scala]
```

> Can we load the script from ExampleScript_1.py or Run_TrackMate_Headless.groovy without pasting it inline?

Yes, you can call it by file path using the Java-side method [`ij.script().run(File, boolean, Object[])`](https://github.com/scijava/scijava-common/blob/scijava-common-2.90.1/src/main/java/org/scijava/script/ScriptService.java#L130-L148). The `ij.py.run_script` Python-side function is [just a wrapper around some `ij.script().run(...)` methods](https://github.com/imagej/pyimagej/blob/1.3.2/src/imagej/__init__.py#L363-L369). You can convert your Python arguments to an `Object[]` using `ij.py.jargs`. If you want to block until script execution is complete, call `get()` on the `Future` returned by `ij.script().run`.

> Also if we have converted the image to ImagePlus format in pyimagej, can we pass the image to macro scripts through args?

Yes, images passed to a macro via SciJava script parameters are automatically converted to string image IDs. So you can do that, and then pass them to macro functions that support passing titles or IDs.

> If so how can we call the passed image file in the the jython?

A Jython script is not an ImageJ macro. ImageJ macro is a specific script language, Jython is a different script language. If you want to pass an `ImagePlus` object to a Jython script, you can write `#@ ImagePlus imp` as a script parameter. If you want to pass an **image file** to a Jython script, you can write `#@ File imageFile` and then pass this file to whatever is expecting a file path.

**Comment by jackyko1991** [comment]
Finally I get things done in two approaches, using python-side and java-side call:

```groovy
//test.ijm
#@ String name
#@ int age
#@ String city
#@ output Object greeting1
greeting = "Hello " + name + "."  + " You are " + age + " years old, and live in " + city + "."
```

On python side we need to load the script file but not parse the path
```python
# define python side arguments
args = {
    'name': 'JK',
    'age': 99,
    'city': 'London'
}

# load the script file
with open('test.ijm')"r") as f:
    script_ijm = f.read()

# Run with ij.py.run_script() function
result = ij.py.run_script('ijm', script_ijm, args)
print(result.getOutput("greeting"))
```

On java side the file need to be handled by java File class object
```python
# define python side arguments
args = {
    'name': 'JK',
    'age': 99,
    'city': 'London'
}

File = sj.jimport('java.io.File')
jfile = File('test.ijm')

# convert python side stuffs to java side
jargs = ij.py.jargs(args)
result_future = ij.script().run(jfile,True,jargs)

# get the result from java future, blocking will occur here
result = ij.py.from_java(result_future.get().getOutput("greeting"))
print(result)
```

Working on the Jython argument parsing as instructed [here](https://stackoverflow.com/a/41340105). Need to test if python side ImageJ1 `imp` or ImageJ2 `dataset` object can be directly parsed, or need to be bridged via `ij.py.window_manager.setTempCurrentImage(imp)` and retrieve the imp in jython through `imp = WindowManager.getCurrentImage()`. Perhaps this need to be run on interactive mode

**Comment by ctrueden** [comment]
@jackyko1991 Did you get everything working? If you are still having issues, please feel free to reopen this issue with details. :smile_cat:
