### ISSUE TITLE
pyimagej not able to convert Views into a python format

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#25]
The following script throws a segfault at `result = ij.py.from_java(inverted)`:
```python
import imagej
from skimage import io

ij = imagej.init()
img = io.imread('https://samples.fiji.sc/new-lenna.jpg')

inverted = ij.op().transform().invertAxisView(ij.py.to_java(img), 1)
result = ij.py.from_java(inverted)
ij.py.show(result)
```
From [this line](https://github.com/imagej/imagej-ops/blob/3ec70376dbade09bd2e843a2f5c2209adf528584/src/main/java/net/imagej/ops/transform/TransformNamespace.java#L533) we know that the line above returns an `IntervalView`. Thus it is `IntervalView` that `ij.py.from_java` needs to know how to convert.

**Comment by ctrueden** [comment]
I tested with scikit-image 0.15.0, and found an unrelated conversion issue, fixed with 4bb4893131751fdc4b9980ae93df6e9b065867c7. Once that was addressed, the above code snippet is working for me, so I'm closing this.
