### ISSUE TITLE
Error on importing imagej on standalone executable using cx_Freeze

### ISSUE THREAD

**Issue by CanYing0913** [imagej/pyimagej#253]
**Describe the bug**
I have the following package in my project: `pyimagej`. However, the name is `imagej` when I actually import it inside python. (That is, when I install the package, I need to use `conda install pyimagej` instead.) I tried with another package `cx_Freeze` to convert my python project to executable by using command `python setup.py build` and ran the application, which pops up the following error:
![image](https://user-images.githubusercontent.com/74372617/226219980-2b4204e8-f895-4e4c-8e19-81fc40e7da9a.png)
**Note**: I did notice under `build/name.platform.pyversion/lib`(it is the folder of my `cx_Freeze` application libraries), it shows a folder called "imagej" instead of "pyimagej" which should make sense since `conda` also named it "imagej".
**THEN** I tried to rename the folder from "imagej" to "pyimagej", and got a new error:
![image](https://user-images.githubusercontent.com/74372617/226220755-e42902a7-ea03-4f18-8fe7-9889d1df4fcb.png)

**NOTE**: I feel like this paragraph is vary important. I don't know if it is a bug regarding `pyimagej`, `scayjava`, or `cx_Freeze`, so I tag everyone involved in this. Sorry to bother.
@ctrueden @marcelotduarte @gselzer 
After carefully inspecting the program flow, I found that the reason here is from `importlib.metadata.from_name()`.  I notice that in [`imagej.__init__.py:60`](https://github.com/imagej/pyimagej/blob/f02b27211c1c48bd30d7b5d91b585c3d2cca411d/src/imagej/__init__.py#L60), it calls [`scajava._versions.py:13`](https://github.com/scijava/scyjava/blob/18294c42cce110934e65aaae7a3f9a828d7e253f/src/scyjava/_versions.py#L13), where it enters [`importlib.util.py:73:find_spec()`] on line 36. It did get the spec, however, when it trys to execute on function `version()` on [line 40](https://github.com/scijava/scyjava/blob/18294c42cce110934e65aaae7a3f9a828d7e253f/src/scyjava/_versions.py#L40), the eventual function is the `importlib.metadata.from_name()`, as suggested in the screenshot. It seems it fails to generate a resolver when I replace `__VERSION__=sj.get_version('pyimagej')` with `__VERSION__=sj.get_version('imagej')` in `imagej/__init__.py` on PyCharm (I was trying to inspect what goes wrong but idk how to debug windows application :() So I guess the reason I got the error in the above screenshots should be the same cause. If anyone would like to take a look and figure out a way to fix it that would be great!

**To Reproduce**
My simple setup.py for cx_Freeze (the application exits on import imagej, so I don't think it is necessary to provide any other files as long as imagej is there):
```python3
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need to be fine-tuned.
build_exe_options = {
    "excludes": ['PyQt5'],
    'packages': ['imagej']
}

# base="Win32GUI" should be used only for Windows GUI app
base = "Win32GUI" if sys.platform == "win32" else None

setup(
    name="pipeline",
    version="0.1",
    description="Test on build for incomplete GUI application",
    options={"build_exe": build_exe_options},
    executables=[Executable("main_GUI.py", base=base)],
)
```
The reason I didn't use `pyimagej` in "includes" is because it cannot find it in that way.

**Expected behavior**
`cx_Freeze` should pack everything and the program should never look for `pyimagej`. (OR it **should** find `pyimagej` as it could in my PyCharm without cx_Freeze application)

**Configuration:**
 - Platform information: Windows 10 64 bit
 - OS architecture): amd64
 - Using anaconda, with pyimagej:1.3.2
 - cx_Freeze version: 6.14.7
 - Python version: 3.8

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by gselzer** [comment]
It seems like this may be a `cx_Freeze` issue as work and issues have moved over there, so I'll close this. We can reopen if there's anything we need to do on pyimagej's side.
