### ISSUE TITLE
I got stuck while running this code

### ISSUE THREAD

**Issue by wzr0108** [imagej/pyimagej#254]
```
ij = imagej.init()
```

**Comment by ctrueden** [comment]
@wzr0108 Did you figure out your issue? We're happy to help if you are still having trouble. By "got stuck" I'm assuming you mean that the code just hangs? If so, that's like just the time it takes to download all the needed JAR file dependencies for ImageJ... but if it hangs for many minutes on a fast connection, then something is going wrong. Anyway, feel free to reopen this issue with more details, or open a new issue, as needed.

**Comment by wzr0108** [comment]
The problem is solved， thank you
