### ISSUE TITLE
How to fully load the .vsi file

### ISSUE THREAD

**Issue by wzr0108** [imagej/pyimagej#255]
My file structure is as follows, \_Image\_ is a folder
```
_Image_
Image.vsi
```

I open the image with the following code
```
ij = imagej.init(headless=False)
image_url = "Image.vsi"
jimage = ij.io().open(image_url)
```
The image has a low resolution
![屏幕截图 2023-03-26 113543](https://user-images.githubusercontent.com/98294772/227753839-bfaafbdc-1ebb-4ac6-9576-3eb7952cb07d.png)

However, my image should contain multiple resolutions

![屏幕截图 2023-03-26 113733](https://user-images.githubusercontent.com/98294772/227753938-48767ddc-49cc-4a5a-95b5-4b84be670366.png)

How to fully load the .vsi file ? thanks

**Comment by elevans** [comment]
Hi @wzr0108,

I'm not very familiar with the `.vsi` file format so there may be a better way than what I found. You can open the entire series by calling the `Bio-Formats Importer` plugin like so:

```python
import imagej

# initialize ImageJ
ij = imagej.init(mode='interactive')

# open the .vsi image series
ij.IJ.run("Bio-Formats Importer", "open=/path/to/image.vsi autoscale color_mode=Default open_all_series rois_import=[ROI Manager] view=Hyperstack stack_order="XYCZT")
```

You can obtain the individual `ImagePlus` images with the `WindowManager`. Accessible via `ij.WindowManager` after PyImageJ has been initialized with the legacy option.
