### ISSUE TITLE
ij.io().open() does not appear to work for absolute paths

### ISSUE THREAD

**Issue by bhacha** [imagej/pyimagej#259]
Hello, I've tried switching to opening my images as `Dataset` objects using `ij.io().open()` but I've found that this method does not work with absolute paths to image files. As an example:
```
import imagej
ij = imagej.init()
imp = ij.io().open(r'C:/Users/Brandon/000012.bmp')
```
returns 
`java.lang.NullPointerException: java.lang.NullPointerException: Cannot invoke "org.scijava.io.location.Location.getName()" because "loc" is null `

There is no error with a relative path, like below.

`imp = ij.io().open(r'000012.bmp')`

This is also not an issue with the `ImagePlus` opener, which handles absolute paths correctly

Update:

I was also able to successfully open an image in a folder using `imp = ij.io().open('image/'+r'000012.bmp')`. The error doesn't seem to be related to the /\ characters

**Comment by ctrueden** [comment]
@bhacha I am guessing this is something related to Windows file paths versus POSIX ones.

Does it work if you write:
```python
imp = ij.io().open(r'C:\\Users\\Brandon\\000012.bmp')
```
?

**Comment by bhacha** [comment]
Ah yep, escaping the backslash instead of using a raw string fixed the issue (and pathlib returned True). I appreciate a simple solution, thanks!
