### ISSUE TITLE
Make `imagej.init()` more resilient

### ISSUE THREAD

**Issue by hadim** [imagej/pyimagej#29]
At the moment when you call twice `imagej.init()` in a notebook (it often happens that I run all the cells from start without restarting the kernel), you get the following error:

```
ValueError: VM is already running, can't set options
```

Don't you think we should be able to call it twice without having Python throwing an error about it? It will silently fail. Maybe we could add a Python warning `import warnings` instead of raising an error.

**Comment by hadim** [comment]
ping @ctrueden (sorry to ping you everywhere Curtis, but I never know when you gonna see the issues, let me know if you want me to stop pinging you :-))

**Comment by hadim** [comment]
Actually, this is a `scyjava` issue: https://github.com/scijava/scyjava/pull/8

**Comment by ctrueden** [comment]
Fixed by #30. Thanks @hadim!
