### ISSUE TITLE
cannot open nii or nii.gz file

### ISSUE THREAD

**Issue by weitongwei** [imagej/pyimagej#292]
`import imagej

ij = imagej.init()

imp = ij.io().open('test.nii')`

[java.lang.Enum.toString] [ERROR] No opener IOPlugin found for FileLocation:file:/K:/py_script_tools/test.nii.

**Comment by NicoKiaru** [comment]
Hello @weitongwei ,

It may be that you need to initialise imagej differently. Please try:

```
ij = imagej.init('sc.fiji:fiji')
```

This should bring the bio-formats library with imagej and allow for opening a variety of file formats.

**Comment by weitongwei** [comment]
Thanks. This works.
