### ISSUE TITLE
Update documentation regarding imagej.server.IJ

### ISSUE THREAD

**Issue by imagejan** [imagej/pyimagej#31]
If I understood correctly, https://github.com/imagej/pyimagej/commit/5ed4dd33363f51675bc87bf3b39c6fdf93d86f43 moved `imagej.IJ` to `imagej.server.IJ`, so this should be reflected in the documentation ([`README.md`](https://github.com/imagej/pyimagej/blob/master/README.md) and [`imagej/server/README.md`](https://github.com/imagej/pyimagej/blob/master/imagej/server/README.md)), right?

**Comment by ctrueden** [comment]
As of pyimagej 1.0.0, the Python client for the ImageJ Server is no longer part of pyimagej. I moved it (back) into imagej-server:

https://github.com/imagej/imagej-server/commit/e940b4d0c166cc16b853ae9918ab9ed87317a7ad
