### ISSUE TITLE
Plugin usage example

### ISSUE THREAD

**Issue by HagaiHargil** [imagej/pyimagej#33]
Hi,

I wish to use the Temporal-Color Code plugin through `pyimagej` but I can't seem to understand how to run plugins using the library.

The basic steps work as expected:
`imagej.init(path_to_fiji))`
`>>> Added X JARs to the Java classpath.`

I can show an image using `ij.py.show()` but as I mentioned - I can't run a plugin. It says that `There are no images open in line 1`, which is true, since I had to close the figure window in order for the script to continue running (the `block` argument from `matplotlib.pyplot.show()` is inaccessible).

When I run the same script from Jupyter with either the `Temporal-Color Code` or the `Mean` plugin (as seen in one of the examples), it returns the following object: `<org.scijava.script.ScriptModule at 0x7fcb802b9258 jclass=org/scijava/script/ScriptModule jself=<LocalRef obj=0x562870b51168 at 0x7fcbe20e95b0>> `, which is a step forward, but I'm still unsure of how to proceed from here.

Thanks in advance.

**Comment by ctrueden** [comment]
@HagaiHargil Did you already study the ["Run a plugin" example in the tutorial notebook](https://nbviewer.jupyter.org/github/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb#Example:-Run-a-plugin:-ij.py.run_plugin)?

If so: could you share a minimal code snippet demonstrating the problem you are seeing?

**Comment by HagaiHargil** [comment]
Thanks for the quick reply. I understand that the ``ScriptModule` repsonse was normal. I'll re-try using Temporal-Color Code specifically.
