### ISSUE TITLE
Issue with thresholding an image

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/pyimagej#42]
Hey all, 

I tried to add some image processing workflow to [this notebook](https://github.com/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb).

In section 4, I added
```
tHuang = ij.op().threshold().huang(cell_colony)
ij.py.show(tHuang);
```

Causing this error:
```
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-6-0327982ad689> in <module>
----> 1 tHuang = ij.op().threshold().huang(cell_colony)
      2 ij.py.show(tHuang);

jnius\jnius_export_class.pxi in jnius.JavaMultipleMethod.__call__()

jnius\jnius_export_class.pxi in jnius.JavaMethod.__call__()

jnius\jnius_conversion.pxi in jnius.populate_args()

jnius\jnius_utils.pxi in jnius.check_assignable_from()

JavaException: Invalid instance of 'net/imagej/DefaultDataset' passed for a 'net/imglib2/histogram/Histogram1d'
```

I uploaded the notebook to the [simplify_tutorials branch](https://github.com/imagej/tutorials/blob/simplify_tutorials/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb), Any hint for getting thresholding to run is appreciated.

Thanks!

Cheers,
Robert

**Comment by ctrueden** [comment]
@haesleinhuepf Thanks for working on it. You're getting bit by multiple method dispatch woes here. Try using `op().run("threshold.huang", cell_colony)` instead?

**Comment by ctrueden** [comment]
Closing, with the assumption that my suggestion fixed it. Please reopen if not.

**Comment by WT215** [comment]
> @haesleinhuepf Thanks for working on it. You're getting bit by multiple method dispatch woes here. Try using `op().run("threshold.huang", cell_colony)` instead?

May I ask how to select background as mask? Where can I find documentation about the parameter setting in `op().run("threshold.huang", cell_colony)`? Many thanks!
