### ISSUE TITLE
Macro Error: Unrecognized command: "TrakEM2"

### ISSUE THREAD

**Issue by sjoyce2** [imagej/pyimagej#44]
I was trying to run the TrakEM2 plugin according to the plugin tutorial here https://nbviewer.jupyter.org/github/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb and I got this error: 

Macro Error: Unrecognized command: "TrakEM2"  in line 1
var ; initializeSciJavaParameters ( ) ; run ( "TrakEM2" , "" <)> ;

I am using Fiji with ImageJ2.

**Comment by ctrueden** [comment]
@sjoyce2 Sorry for the delay in reply!

How are you initializing ImageJ? Wrapping a local installation? Or from a remote Maven artifact? Also, are you running headless? Or with GUI? And finally, which OS?

If you have a short sample Python script I could use to reproduce the issue, that would be helpful.

**Comment by ctrueden** [comment]
Hmm, this may be the same issue as #36. I haven't had time to work on it deeply yet, unfortunately.

**Comment by ctrueden** [comment]
@sjoyce2 I'm going to assume you are using the remote Maven artifact approach (`sc.fiji:fiji`) as opposed to wrapping a local installation—in which case, #36 is the more general issue in play here. So I'll close this issue in favor of that one.
