### ISSUE TITLE
Working with Plugins: WindowManager.getCurrentImage() doesn't work

### ISSUE THREAD

**Issue by ChasNelson1990** [imagej/pyimagej#51]
Trying to use a plugin within a Python kernel Jupyter Notebook, as per the tutorial (https://nbviewer.jupyter.org/github/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/6-ImageJ-with-Python-Kernel.ipynb section 6.2).

However, my output from `WindowManager.getCurrentImage()` is the same both before and after running `ij.py.run_plugin()`. Any ideas?

My code (using pyimagej 0.4 as that's what's on conda forge):

```python
ij = imagej.init('/home/chas/Fiji.app', headless=False)

# Load UI and send NumPy Array
ij.ui().showUI()
np_Slice = np_allChannels[26,:,:,0].copy()
ij.ui().show('Image',ij.py.to_java(np_Slice))

# Run Plugin
plugin = 'Mean'
args = { 
    'block_radius_x': 100,
    'block_radius_y': 100
}
ij.py.run_plugin(plugin, args)

# Create a window manager for interacting with the UI
windowManager = jnius.autoclass('ij.WindowManager')

# Get back data
results = ij.py.from_java(windowManager.getCurrentImage())
display(np_Slice-results)

# Display
f, axes = plt.subplots(1,2)  # Create one subplot (1x1 grid)
(aO, aM) = axes.flatten()

aO.grid(False)
aO.imshow(np_allChannels[26,:,:,0], cmap='gray', interpolation='none')

aM.grid(False)
aM.imshow(results, cmap='gray', interpolation='none')

plt.show()
```

My data `np_allChannels` is a 52x1024x1024x4 numpy array of `float64` dtype.

**Comment by ChasNelson1990** [comment]
See also my issue on the imageJ tutorials repo: https://github.com/imagej/tutorials/issues/78

**Comment by mpinkert** [comment]
Sorry this took so long to respond to; we had to track down this down to a synchronization bug between ImageJ1 and ImageJ2.  This is not actually the same issue as imagej/tutorials#78.  What is happening here is that the plugin modifies the `ImagePlus` for the open image, but does not properly modify the linked `Dataset` or `ImageDisplay`.  Most ways of accessing the ImagePlus data will actually link back to the `Dataset`, so you never get the modified values and they are in fact overwritten by the original ones.

We are working on a proper bug fix for this issue, but for now here is a way of getting the data out programmtically.

```python
imp = windowManager.getCurrentImage()
stack = imp.getStack();
stack.setPixels(imp.getProcessor().getPixels(), imp.getCurrentSlice());
```
The `setPixels` command should update the `Dataset` and `ImageDisplay` properly.

In addition, if you have a multi-slice image and change slices, the data will sync properly.  However, if you subsequently modify the latest slice and do not move from that slice, it will still require the above code to synchronize the data.

**Comment by ctrueden** [comment]
With pyimagej 1.2.1, the `ij.py.run_plugin` now accepts an optional `imp` argument for setting the active image. And `run_plugin` now invokes `ij.IJ.run` to execute the command instead of doing something crazy with `run_macro` under the hood. See also #126.

If you are using `run_macro` rather than `run_plugin`, for the moment you'll need to call `ij.py.to_imageplus(np_Slice).show()` to register the `np_Slice` as an `ImagePlus` with ImageJ, which should make it become the active image, so that the macro operates on the right thing. See also #97.

**Comment by jbychang** [comment]
Hi folks—I was running `ij.IJ.run(imp, "Subtract Background...", "rolling=50")` and ran into this same issue; adding the code above (reproduced below) solved the issue:

```
stack = imp.getStack();
stack.setPixels(imp.getProcessor().getPixels(), imp.getCurrentSlice());
```

Perhaps something needs to be fixed in `ij.IJ.run()`?
