### ISSUE TITLE
imagej.server no installed by conda

### ISSUE THREAD

**Issue by ChasNelson1990** [imagej/pyimagej#52]
I recently installed pyimagej through conda, as per your instructions (in fact I installed conda for the first to do it as I mush prefer pip). I note that this installs version 0.4.0 and not the latest release.

However, when I try to access `imagej.server.IJ()` I seem unable to. I have tried:
```python
import imagej
test = imagej.server.IJ()
```
and
```python
import imagej
test = imagej.server().IJ()
```
and
```python
import imagej.server as ijserver
test = ijserver.IJ()
```
All to no avail.

I then when into anaconda's tree and realised the pyimagej bins don't actually have the imagej.server file.

Is this meant to be included in the package?

**Comment by ctrueden** [comment]
Thanks for the report, @ChasNelson1990!

The exclusion of the imagej.server subpackage is unintentional.

> I note that this installs version 0.4.0 and not the latest release.

Thanks for the heads up about that. The pyimagej 0.5.0 is relatively recent and I guess the conda-forge tooling didn't pick it up. I'll try to investigate that soon.

**Comment by ChasNelson1990** [comment]
No problem.

**Comment by manf1984** [comment]
@ctrueden 
Is there a way to obtain the imagej.server subpackage and use its functions?
Thanks!

**Comment by ctrueden** [comment]
@manf1984 We will release pyimagej 0.6.0 soon which will include the imagej.server subpackage. In the meantime, the packaging is fixed on the master branch, so you could use that as a stopgap for now.

@ChasNelson1990 Thanks again for the report. And BTW, pyimagej 0.5.0 is now on conda-forge.

**Comment by manf1984** [comment]
@ctrueden Thank you very much! Great!
