### ISSUE TITLE
importing imagej into spyder

### ISSUE THREAD

**Issue by MantisShrimp2** [imagej/pyimagej#58]
Hello,

I am trying to import the imageJ module into python, i use spyder on Linux. once i try to import imageJ i receive this error:

ModuleNotFoundError: No module named 'jnius_config'

i thought downloading pyjnius module would solve the issue but it hasn't. I've downloaded pyimage through conda on my terminal. 

what should i do to get ImageJ working? thank you

**Comment by ctrueden** [comment]
@MantisShrimp2 Does this help? https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

**Comment by ctrueden** [comment]
@MantisShrimp2 I'm going to assume that link helped. :smile: Please reopen if you are still stuck.
