### ISSUE TITLE
Can't Find Stats Attribute

### ISSUE THREAD

**Issue by gfleetwood** [imagej/pyimagej#59]
I'm using pyimagej on Ubuntu 18.04 in a conda environment with Python 3.6 and a system running OpenJDK 11.

This is part of the script I'm running trying to reproduce someone's work:

```
ij = imagej.init()
img = io.imread(filename1)
fiji_image = rgb2gray(img)
number = ij.op().stats().mean(fiji_image)
```
And it's throwing this error on the last line:

```
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "od-calc.py", line 50, in <module>
    number = ij.op().stats().mean(fiji_image)
AttributeError: 'net.imagej.ops.OpService' object has no attribute 'stats'
```

Checking the documentation the location of the stats module is correct. What could be the problem?

**Comment by ctrueden** [comment]
@gfleetwood Hmm, I cannot reproduce this in my environment, but a similar issue (probably same root cause) is reported in #57.

What versions of the Java components are you using?
```python
>>> ij.getVersion()
'2.0.0-rc-71'
>>> 'stats' in dir(ij.op())
True
>>> from jnius import autoclass
>>> VersionUtils = autoclass('org.scijava.util.VersionUtils')
>>> OpService = autoclass('net.imagej.ops.OpService')
>>> VersionUtils.getVersion(OpService)
'0.43.2'
```

**Comment by imagejan** [comment]
@ctrueden wrote:
> a similar issue (probably same root cause) is reported in #57

Also similar (and *maybe* related):
https://github.com/scijava/scyjava/issues/13

and the current CI test failures in https://travis-ci.com/scijava/scyjava/builds/144567648

```
AttributeError: 'org.scijava.table.DefaultFloatTable' object has no attribute 'setColumnHeader'
```

**Comment by imagejan** [comment]
@gfleetwood can you try downgrading your `pyjnius` version to 1.2.0? See https://github.com/kivy/pyjnius/issues/465.

**Comment by gfleetwood** [comment]
I have the same version of the ij component. Sorry, I jumped to downgrading pyjnius before checking that one. The downgrade worked for finding the stats module but the mean function is now throwing an error. Upgrading to Python 3.7 didn't fix it.

```
$ python 3_img_2_od.py > logs.txt
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "3_img_2_od.py", line 48, in <module>
    number = ij.op().stats().mean(fiji_image)
  File "jnius/jnius_export_class.pxi", line 1034, in jnius.JavaMultipleMethod.__call__
jnius.JavaException: No methods matching your arguments, available: ['(Ljava/lang/Iterable;)Lnet/imglib2/type/numeric/RealType;', '(Lnet/imglib2/type/numeric/RealType;Ljava/lang/Iterable;)Lnet/imglib2/type/numeric/RealType;']
```

**Comment by imagejan** [comment]
@gfleetwood please try using `ij.py.to_java()` as shown in the README example:

```
number = ij.op().stats().mean(ij.py.to_java(fiji_image))
```

**Comment by gfleetwood** [comment]
@imagejan Now I'm getting this error:

```
Traceback (most recent call last):
  File "3_img_2_od.py", line 49, in <module>
    number = ij.op().stats().mean(ij.py.to_java(fiji_image))
  File "jnius/jnius_export_class.pxi", line 1044, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 760, in jnius.JavaMethod.__call__
  File "jnius/jnius_conversion.pxi", line 78, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 205, in jnius.check_assignable_from
jnius.JavaException: Invalid instance of 'net/imglib2/python/ReferenceGuardingRandomAccessibleInterval' passed for a 'java/lang/Iterable'
```

**Comment by imagejan** [comment]
I am not sure if the Java version is an issue. But it might be simply a wrong usage of the `mean` op. As far as I can tell, it only accepts `Iterable`s, so you can transform your argument first with `flatIterableView`:

```
number = ij.op().stats().mean( ij.op().transform().flatIterableView( ij.py.to_java(fiji_image) ) )
```

For further questions and discussion of `imagej-ops` usage, I recommend starting a new topic on https://forum.image.sc.

**Comment by gfleetwood** [comment]
That works for me. Thanks for all the help.
