### ISSUE TITLE
Synchronize IJ1 in headless mode

### ISSUE THREAD

**Issue by mpinkert** [imagej/pyimagej#70]
The xarray pull request imagej/pyimagej#56 allow the user to synchronize IJ1 data structures when headless=False.  However, the functions do not address the use case of ImageJ1 data processing that is done headlessly. 

This is, to some degree, actually a problem for imagej/imagej-legacy synchronization, but should be kept in mind as an edge case that may become an issue for some users.

**Comment by ctrueden** [comment]
This is indeed a critical requirement: robust support for ImageJ (1.x) data structures while in headless mode. Much of that work is not PyImageJ-specific, but needs to happen in the imagej-legacy layer. However, this issue as written is very general, and exactly which features do or do not work headless is not described. So it's hard to use this issue as a starting point for doing work. The [issues tagged with `headless`](https://github.com/imagej/pyimagej/labels/headless), as well as some issues in imagej-legacy such as imagej/imagej-legacy#153, imagej/imagej-legacy#185, and imagej/imagej-legacy#264 cover needed work (both in scope for the paper, and beyond scope) in a more specific and granular way. So I'm closing this issue in favor of those.
