### ISSUE TITLE
pyimagej not working with installation instructions on Linux

### ISSUE THREAD

**Issue by Dino-Fossil** [imagej/pyimagej#71]
Hello!

Apologies if using the wrong communication channel.
For the last two days, I've tried getting pyimagej to work following the instructions on the project page.
I've been using a fresh installation of anaconda on Manjaro Linux and Linux Mint 19.3, both with similar results.
First, trying 
`import imagej`
`ij = imagej.init('path_to_my_Fiji_installation')`
`ij.getVersion()`

resulted in complaints and errors about jnius not finding libjvm.so something is wrong apparently...

Eventually, I manually installed openjdk8 (Manjaro is by default using a newer openjdk) and set $JAVA_HOME pointing towards it (previously it seemed to point towards my anaconda directory).
This seems to help to some degree, as I was now able to at least get pyimagej to import imagej and display images.
However, once I tried using any more elaborate commands (again following the examples from  the Jupyter notebook linked on the project page), the issues continued.
Any attempt at using commands of the form
`ij.op().XXX()` 
will result in 

> AttributeError: 'net.imagej.ops.OpService' object has no attribute 'XXX'

That happens also when copy-pasting code from the Jupyter notebook, using different versions of ImageJ (local and not local), etc.

I would be very grateful for any help with troubleshooting...

**Comment by glyg** [comment]
HI I just came across the same issue, 
it looks related to pyjnius not searching for the libjvm.so at the correct place. In the source for pyjnius the path is correct though:
[`lib_location = 'jre/lib/{}/server/libjvm.so'.format(cpu)`](https://github.com/kivy/pyjnius/blob/master/jnius/env.py)

Which in my case refers correctly to `~/miniconda3/envs/pyimagej/jre/lib/amd64/server/libjvm.so`
I tried updating through pip and conda to no avail.

**Comment by glyg** [comment]
oops I responded on the wrong issue, sorry for the noise

**Comment by mpinkert** [comment]
This is an issue with the current version of pyjnius (see imagej/pyimagej#72 and kivy/pyjnius#481).

Can you try installing pyjnius version 1.2.0 and see if that fixes the issue?

**Comment by Dino-Fossil** [comment]
Thank you very much for the suggestion!
After a first quick test that seems to help - at least I don't get the error messages anymore.
More elaborate testing will have to wait until tomorrow, though. :)

**Comment by ctrueden** [comment]
PyImageJ version 1.0.0 is now released, and uses JPype instead of PyJNIus. So this issue should disappear now. Please reopen if you continue to have problems with it!
