### ISSUE TITLE
Yet another libjvm.so issue

### ISSUE THREAD

**Issue by glyg** [imagej/pyimagej#72]
Hi all, thanks for your work

I fell on a libjvm.so not found error after installing pyimagej today. 
Turns out this is due to a [bug](https://github.com/kivy/pyjnius/issues/481) in pyjnius 

A quick fix is to not name your environment pyimagej but rather ijpy, for example.

**Comment by mpinkert** [comment]
Thanks for posting this.  You can also get around this by specifying `pyjnius=1.2.0` to use a working version of pyjnius.  

We will be specifying a working version to install in a upcoming release until they fix this bug.

**Comment by glyg** [comment]
Ok good to know! Feel free to close this, I opened it mainly for documentation purposes
