### ISSUE TITLE
ij.py.synchronize_ij1_to_ij2 breaks for IJ1 created images

### ISSUE THREAD

**Issue by mpinkert** [imagej/pyimagej#74]
The synchronize function only works for images created in IJ2, then sent to IJ1, which have an underlying `ImageJVirtualStack` as their stack.

Prior to a recent patch, you would get an error in the following use case:

```python
import imagej
ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
ij.py.run_macro("""run("Blobs (25K)");""")
blobs = ij.py.get_image_plus()
```
That `stack.setPixels()` requires an `Object` and instead got a `ByteArray`.

I've patched this particular case using a quick check (on an upcoming pull request), but this is not a general solution and there are probably other cases where this will break.  A more general solution would be better.

Here is the current check:
```python
if str(type(pixels)) == '<class \'jnius.ByteArray\'>':
    return
```

Please post other instances of this bug if you find them!

**Comment by elevans** [comment]
We tested this and it looks like this is no longer an issue. Calling `sync_image()` on blobs as above does not crash.
