### ISSUE TITLE
No Module named 'ij' Error

### ISSUE THREAD

**Issue by mattgbiz** [imagej/pyimagej#79]
Hi, I have been trying to use the imagej wrapper to execute some code that I have written using imagej scripting with a python script for a separate function controlling an external device (a rotational stage). 

![ImageJ Problem](https://user-images.githubusercontent.com/33110348/82372579-36435200-99ea-11ea-8c78-474999d41a77.JPG)

Above is a snip from my Anaconda Prompt (miniconda3). I am unsure why there is an error that comes from initializing imagej but then seems to have successfully initialized when I run  ij.getVersion(). I also am unsure why it cannot find the module ij. Below is the top of the script that I wrote within the Fiji scripter that functions properly. 

![FijiScript](https://user-images.githubusercontent.com/33110348/82373007-e9ac4680-99ea-11ea-9fe2-dc837c03e4d5.JPG)

I am curious if this error in finding the ij module comes from the difference between python 2 and python 3 syntax. I am fairly new to coding in python so any help would be great.

**Comment by ctrueden** [comment]
@mattgbiz Great that you got PyImageJ initialized successfully!

Your error is not related to Python 2 versus Python 3, but rather differences in Jython versus the pyjnius library which PyImageJ uses.

The Jython library makes importing Java classes very easy, via a syntax analogous to importing Python modules. But you have to write it differently for pyjnius.

Jython version:
```jython
from ij.gui import GenericDialog
```

pyjnius version:
```python
from jnius import autoclass
GenericDialog = autoclass('ij.gui.GenericDialog')
```

The variable `GenericDialog` will then contain a Java class reference to that class, which can be used in (mostly) the same way as from Jython. I _think_ the rest of your script after the imports should work as-is, although I didn't test it.

**Comment by mattgbiz** [comment]
Hello @ctrueden 

I appreciate the initial help on this issue. I had mixed success with these solutions. The first solution and second solutions both seemed to have errors. Below are three images, the first is the script that I would like to be able to run in python which operates properly on Fiji (sorry that I have switched it up from the dialog, the functionality of that first script I had posted was mainly trying to do this function with a dialog box that serves another purpose). The second is what resulted from your first fix and the third is what resulted from your second fix.

![FijiExample](https://user-images.githubusercontent.com/33110348/82504529-a2e14e00-9ac9-11ea-8749-df7b9c4b7901.JPG)
![Attempt1](https://user-images.githubusercontent.com/33110348/82504539-a674d500-9ac9-11ea-8541-fb99aa03d514.JPG)
![AnacondaWindow](https://user-images.githubusercontent.com/33110348/82504543-a96fc580-9ac9-11ea-8604-53961cd4e842.JPG)

A final question I have with the second method as it seemed to show more promise for me. If I wanted to use a script written and saved as a .py in some other text editor, how would i run that in ij.script().run() format? Does it need to be saved to a specific location that is on path? What are the second and third arguments of .run()? 

Thanks again for the help so far.

**Comment by imagejan** [comment]
* In your "first fix" trial: `autoclass(os.path)` won't work because `os` is a Python module, not a Java package. You only `autoclass` Java classes.

* In you "second fix" trial: How do you expect any image to be opened when you start from the python prompt? As far as I can see, you never open an image.

In general, I wouldn't rely on `WindowManager` when running a script headless anyway. You can either use a script parameter input (`#@ ImagePlus imp`), or open you image file in the script using `IJ.openImage()`.
