### ISSUE TITLE
No plugins loaded with imagej.init('sc.fiji:fiji')

### ISSUE THREAD

**Issue by supersergiy** [imagej/pyimagej#82]
As far as I understood from documentation, initializing `ij` with `imagej.init('sc.fiji:fiji')` should load all the standard Fiji packages. However, when I attempted to run it only 1 JAR was loaded (`Added 1 JARs to the Java classpath.`) and I was unable to load classes from TrakEM2 package.

The same code works when given a path to the local Fiji installation, but it would be great if `imagej.init('sc.fiji:fiji')` would work.

**Comment by imagejan** [comment]
See https://github.com/imagej/pyimagej/issues/36.

I think this is fixed on `master`. @supersergiy how did you install `pyimagej`?

**Comment by ctrueden** [comment]
We need to release a new Fiji with all the latest components. In the meantime, see if `imagej.init('sc.fiji.fiji:net.imagej:imagej-legacy:0.37.4')` works any better?

**Comment by ctrueden** [comment]
In my hands today, `imagej.init('sc.fiji:fiji')` works and initializes with Fiji version 2.1.1, which includes imagej-legacy 0.37.4.

@supersergiy Please `rm -rf ~/.jgo` and try again. And if it still doesn't work for you, please reopen this issue!
