### ISSUE TITLE
Documentation for API and correspondence with GUI

### ISSUE THREAD

**Issue by b2jia** [imagej/pyimagej#83]
I've been looking everywhere in the API for "Process -> Find Maxima", but I've been unable to find documentation for this function. Where is the best place to look?

**Comment by imagejan** [comment]
(In general: questions like this are best asked on https://forum.image.sc.)

The *Process > Find Maxima* command is an ImageJ1 command. In the GUI, you can type `Find Maxima` in the search bar and press the <kbd>Source</kbd> button, and it will open this:

https://github.com/imagej/ImageJA/blob/232620e0a3b0fd33bb22083aaadb2c26b1a31fc6/src/main/java/ij/plugin/filter/MaximumFinder.java

You can also have a look at https://javadoc.scijava.org for the Javadoc, in your case it will be in the ImageJ1 component here:

https://javadoc.scijava.org/ImageJ1/index.html?ij/plugin/filter/MaximumFinder.html

Note that in order to access ImageJ1 plugins from `pyimagej`, you'll have to have `imagej-legacy-0.37.4` on the class path (see also https://github.com/imagej/pyimagej/issues/82#issuecomment-647745639).

**Comment by b2jia** [comment]
Thanks for the advice. It is still unclear to me how to access this from ```pyimagej```. For instance, ```Find Maxima``` is found under _Process_  > in the GUI. In ```pyimagej```, there is no ```ij.process()```. It is not obvious to me (and perhaps others that are uninitiated with ```pyimagej``` but perhaps more familiar with the GUI) that this would be found under eg. ```ij.op()``` or ```ij.plugin()```.

**Comment by b2jia** [comment]
It may also be an issue of not being able to find ImageJ1 plugins. I wonder if this is diagnostic of my error:

```
import imagej
ij3 = imagej.init('sc.fiji:fiji+net.imagej:imagej-legacy:0.37.0-SNAPSHOT')

java_img = ij3.py.to_java(my_img)
ij3.py.run_macro("""run("Find Maxima...", "prominence=2000 strict exclude output=List");""")
```

returns a NullPointerException.

**Comment by imagejan** [comment]
> `0.37.0-SNAPSHOT`

I think you need specifically version `0.37.4` or later of `imagej-legacy`. Did you test that?

**Comment by b2jia** [comment]
Yes, I tried ```0.37.4``` as well. I saw a similar discussion suggesting to use ```imagej-lecacy:0.37.0-SNAPSHOT``` and I tried both, returning the same error.

**Comment by lizhogn** [comment]
> It may also be an issue of not being able to find ImageJ1 plugins. I wonder if this is diagnostic of my error:
> 
> ```
> import imagej
> ij3 = imagej.init('sc.fiji:fiji+net.imagej:imagej-legacy:0.37.0-SNAPSHOT')
> 
> java_img = ij3.py.to_java(my_img)
> ij3.py.run_macro("""run("Find Maxima...", "prominence=2000 strict exclude output=List");""")
> ```
> 
> returns a NullPointerException.

If possible, can you check the #86 issue that I meet, maybe you encountered the same problem before. thanks very much.

**Comment by ctrueden** [comment]
One general way to replicate an ImageJ command in PyImageJ is:

1. Run the Macro Recorder (Plugins > Macros > Record...) and change to JavaScript mode. The Recorder window will pop up.
2. Execute your command.
3. Check the output in the Recorder window and adapt it to Python accordingly.

When I do this with Find Maxima, I see:
```javascript
IJ.run(imp, "Find Maxima...", "prominence=10 output=[Point Selection]");
```

This is an ImageJ1 command, so I try pyimagej's `run_plugin` function as follows:
```python
ij.py.run_plugin("Find Maxima...", args={"prominence": 10, "output": "Point Selection"})
```

I'm short on time now, but will test this tomorrow and report back with further details.

**Comment by elevans** [comment]
@b2jia 

I've just added a new notebook to our PyImageJ tutorials, [8-Discover-and-run-ImageJ-commands](https://github.com/imagej/pyimagej/blob/master/doc/8-Discover-and-run-ImageJ-commands.ipynb), that outlines how to use the ImageJ Recorder to discover the ImageJ command API and run those commands with PyImageJ. 

You can find that notebook in the [`pyimagej/doc`](https://github.com/imagej/pyimagej/blob/master/doc) directory. As we get more feedback we will add/improve the notebook going forward.
