### ISSUE TITLE
How can we use the set measurement function in Imagej through pyimagej?

### ISSUE THREAD

**Issue by oximi123** [imagej/pyimagej#84]
'set measurement' function can be found by Analyse -> Set Measurements

**Comment by elevans** [comment]
@oximi123 


I've just added a new notebook to our PyImageJ tutorials, [8-Discover-and-run-ImageJ-commands](https://github.com/imagej/pyimagej/blob/master/doc/8-Discover-and-run-ImageJ-commands.ipynb), that outlines how to use the ImageJ Recorder to discover the ImageJ command API and run those commands with PyImageJ. 

You can find that notebook in the [`pyimagej/doc`](https://github.com/imagej/pyimagej/blob/master/doc) directory. As we get more feedback we will add/improve the notebook going forward.
