### ISSUE TITLE
Improve doc examples content and structure

### ISSUE THREAD

**Issue by mmarras** [imagej/pyimagej#93]
Dear all, 

I'd like to see a more in-depth how-to-use pyimagej. I have followed the recommendation to raise use questions at image.sc. Please see here for my recent post to ask for more explanation on [how-to-use](https://forum.image.sc/t/first-steps-with-pyimagej-after-installing-applying-run-macro-to-image/45199) `run_marco()`. The feedback rate is very low, i.e., none for pyimagej.

Maybe improvements can be twofold:

1. An improved verbal description of what can be done with the pyimagej package (maybe in terms of use-cases), so the right expectations are set before people start to invest time.
2. An improved notebook on how to use PyImageJ.

**Comment by ctrueden** [comment]
As of 38a52b3381efc496c0391d12cc197ab6885900c9, the new `doc` folder goes into more technical details with better organization. Also, more notebooks are nearing completion; will reply again here about that soon. But it still won't reach the level of your request, @mmarras. The PyImageJ developers aren't bioimage analysts, we're research software engineers, and so we don't have an in-depth real-world image analysis workflows. There have been a couple posted on forum.image.sc, but no one is curating them. It could be you, if you want to contribute.

**Comment by mmarras** [comment]
That would be worthwhile to pick up. You have a recommendation on where to start?

Any update? Otherwise?

**Comment by imagejan** [comment]
I'd also be interested in seeing a (curated) list of real-world use cases for `pyimagej` (maybe right in the README?).

One example is https://github.com/PMEAL/porespy that [uses some ImageJ filters](https://github.com/PMEAL/porespy/blob/de7020f576c45544af02fe51c1162cdbeb90afa6/porespy/imagej/__funcs__.py) via `pyimagej`.

**Comment by ctrueden** [comment]
@mmarras @imagejan I have pushed some improvements to the READMEs. There is now a section collecting real-world examples; see `doc/examples/README.md`. It's pretty bare, but you are welcome to add more items to the list.

There is also a new `doc/README.md` that links to the numbered tutorial sequence, as well as reference documentation.

If you feel anything is missing, you can reply back here, or open a new issue.
