### ISSUE TITLE
Windows : AttributeError: module 'scyjava' has no attribute 'jvm_started'

### ISSUE THREAD

**Issue by AymericFerreira** [imagej/pyimagej#98]
Hello,

I installed PyimageJ through Conda in Windows 10. 

When I try to initialise it I receive an error :

```
>>> import imagej
>>> imagej.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Anaconda3\envs\imagej\lib\site-packages\imagej\__init__.py", line 114, in init
    if sj.jvm_started():
AttributeError: module 'scyjava' has no attribute 'jvm_started'

```

JAVA_HOME, JDK_HOME and PYJNIUS_JAR are set :

```
>>> os.environ["JAVA_HOME"]
'D:\\Programs\\Anaconda3\\envs\\imagej\\Library'
>>> os.environ["JDK_HOME"]
'D:\\Programs\\Anaconda3\\envs\\imagej\\Library'
>>> os.environ["PYJNIUS_JAR"]
'D:\\Programs\\Anaconda3\\envs\\imagej\\share\\pyjnius\\pyjnius.jar'
```

Can it be related to the recent updates of scyjava ? https://github.com/scijava/scyjava

**Comment by imagejan** [comment]
@AymericFerreira what versions of `pyimagej`, `scyjava` and `imglyb` are in your conda environment?

You should have:
```
> conda env list

[...]

imglyb                    1.0.0
pyimagej                  1.0.0
scyjava                   1.1.0
```

**Comment by AymericFerreira** [comment]
Thank you for your quick answer. I don't really know what I did, I tried to turn around some error and pyimagej was probably not the problem. 
In my latest environnement I have not such problem and as you said I have the good versions for imglyb, pyimagej and scyjava. 
Everything is working now
Sorry about this and again thank you.
